DLR-AMR/t8code

example/ghost/Makefile.am
example/ghost/t8_test_ghost_large_level_diff.cxx
src/t8_cmesh/t8_cmesh_vtk.c
src/t8_forest/t8_forest_partition.cxx

Feature ghost v3

---

test/Makefile.am
test/t8_test_find_parent.cpp

I implemented a test, that checks if the parent of an element was computed correctly

Added test for parent-child-relation

---

src/t8_forest/t8_forest_adapt.cxx

Drastically increase the number of comments in t8_forest_adapt.
Some minor edits of the code. Only quality of life.

Feature comments in adapt

---

src/t8_forest.h
src/t8_forest/t8_forest.c
src/t8_forest/t8_forest_types.h
test/Makefile.am
test/t8_test_user_data.cxx

- Add a user function pointer to the forest.
- Add a test for forest user data and function pointer

Add a user function pointer to the forest

---

example/basic/basic_hcube.cxx
example/cmesh/t8_cmesh_load_save.cxx
example/ghost/t8_test_face_iterate.cxx
example/ghost/t8_test_ghost.cxx
example/ghost/t8_test_ghost_large_level_diff.cxx
example/gmsh/t8_read_msh_file.cxx
example/tetgen/t8_forest_from_tetgen.cxx
example/tetgen/t8_read_tetgen_file.c
example/tetgen/t8_time_tetgen_file.c
example/timings/t8_time_prism_adapt.cxx
example/triangle/t8_read_triangle_file.cxx
src/t8_cmesh/t8_cmesh.c
src/t8_cmesh/t8_cmesh_partition.c
src/t8_cmesh/t8_cmesh_readmshfile.c
src/t8_cmesh/t8_cmesh_save.c
src/t8_cmesh/t8_cmesh_trees.c
src/t8_cmesh/t8_cmesh_vtk.c
src/t8_forest/t8_forest_partition.cxx
src/t8_forest/t8_forest_vtk.cxx
src/t8_schemes/t8_default/t8_default_quad_cxx.cxx
src/t8_vtk.c

Fixed all t8code related compiler warnings for gcc 8.4.0.

fix compiler warnings

---

src/t8_cmesh.h
src/t8_cmesh/t8_cmesh.c

- Add dimension parameter to empty cmesh creation
- Add a t8_cmesh_is_empty function

feature improve empty cmesh

---

src/t8_cmesh/t8_cmesh.c

Duplicating the communicator and checking for congrunence in the communicator.

Closes #69

---

src/t8_cmesh/t8_cmesh.c

Print an error message when cmesh hypercube is called with partition flag.
See #79

Feature error message in cmesh hypercube

---

src/t8_forest.h
src/t8_forest/t8_forest_cxx.cxx
test/Makefile.am
test/t8_test_point_inside.cxx

Implement a check whether a point lies inside an element and add a test.
Also required to implement face normals for lines.
Note: PR #74  depends on this PR

Point inside check

---

example/netcdf/t8_write_cmesh_netcdf.c
example/netcdf/t8_write_forest_netcdf.cxx
src/t8_cmesh/t8_cmesh_netcdf.c
src/t8_cmesh_netcdf.h
src/t8_forest/t8_forest_netcdf.cxx
src/t8_forest_netcdf.h
src/t8_netcdf.c
src/t8_netcdf.h

Added functions to write out a forest or cmesh in netCDF-4 Format

Feature write netcdf files

---

example/cxx/t8_cxx_elements.cxx
src/t8_cmesh/t8_cmesh_testcases.c
src/t8_cmesh/t8_cmesh_testcases.h
src/t8_schemes/t8_default/t8_default_vertex_cxx.cxx
src/t8_schemes/t8_default/t8_dprism.h
src/t8_schemes/t8_default_cxx.hxx
test/t8_test_cmesh_partition.cxx
test/t8_test_forest_commit.cxx
test/t8_test_ghost_and_owner.cxx

- Indent cmesh testcases
- Start indenting unindented files
- Finish indenting unindented files

fix indentation

---

.github/workflows/tests.yml

- Use ubuntu:latest
- Activate sc and p4est tests

CI improvements

---

.github/workflows/tests.yml
example/tutorials/t8_step1_coarsemesh.c
src/t8_forest/t8_forest_cxx.cxx
test/t8_test_point_inside.cxx

- Activate Werror in the CI
- Remove all warnings that occur in the CI

Feature remove all warnings

---

src/t8_forest/t8_forest_vtk.cxx

By using the vtkCell base class we can spare one of
the lengthy switch/case statements and have shorter,
cleaner code.

Simplify vtk code by using vtkCell base class

---

.github/workflows/tests.yml

The Ci should now run at 1:10 am UTC every night.

Feature ci nightly

---

README.md

Added a new images to the README.
Arranged images in README in table.

Feature readme airplane image

---

thirdparty/README.md

Add a README file with update instructions for googletest.

Create README for update instructions of googletest

---

src/t8_cmesh/t8_cmesh_trees.c
src/t8_forest/t8_forest.c
src/t8_forest/t8_forest_cxx.cxx
src/t8_schemes/t8_default/t8_dtri_bits.c

Personal prints (debugf) have been removed.

Remove comments

---

.github/workflows/mattermost.yml

This is a test PR with an updated message

Updated workflow

---

.github/workflows/mattermost.yml

Feature mattermost messages test

---

.github/workflows/mattermost.yml

Send different messages for merges, pushs and pull_request

Feature ci mattermost messages

---

test/Makefile.am
test/t8_gtest_nca.cxx

Currently, there is no test to check the computation of the nearest common ancestor for each element.
This PR implements such a function. Testing for pyramids is skipped in general. Two tests are implemented.
Test 1: nca_check_shallow
check the nca for all combination of children of the root-element
Test 2: nca_check_deep
Compute elements up to level 10 and check from the current level on the nca for the first and last descendant of this element. The first and last descendant must have this active element as the nca, This test is different for T8_ECLASS_VERTEX as the first/last descendant logic is not valid for vertices. Instead, the nca is checked for the correct level.
If the Pull request indroduces …

Feature nca test

---

src/Makefile.am

The compiled t8 libraries now link correctly against p4est and sc.
See also #224 

Feature sc linkage

---

.github/workflows/check_indentation.yml
src/t8_cmesh/t8_cmesh_offset.c

IMPORTANT: Merge #236  first.
Added a github action that checks whether the code is properly indented or not.
This action executes the script `check_if_all_files_indented.scp` and passes when the script passes.
The output of the script is uploaded as an artifact.

Feature ci indent as GitHub action

---

test.txt

Testing whether we can close issue by explicitely stating: fixes #240 

Add a test file

---

src/t8_cmesh/t8_cmesh_examples.h

Add Documentation for hybrid hypercube example

---

test/t8_schemes/t8_gtest_nca.cxx

Implemented recursive tests for the nca to test this function for a large amount of possible inputs and up to the maximal refinement level.

Feature recursive nca testing

---

test/t8_gtest_version.cxx

Increased in the version number to 0.91.0 in preparation of release.
This should be merged before #287 

increase version number in tests

---

test/t8_gtest_version.cxx

update to version v0.11.0

---

tutorials/Makefile.am

The tutorial headers where missing from the installed headers.

add missing tutorial headers to makefile

---

.gitmodules

Text was not aligned in the .gitmodule file.
Replaced spaces with tabs in the ignore lines.

Use tabs in .gitmodule file to align text

---

example/IO/cmesh/netcdf/Makefile.am

The name of this variable was not correct. This PR fixes it.

Update Source name in makefile

---

src/t8_element_c_interface.cxx
src/t8_element_c_interface.h
src/t8_element_cxx.hxx

I updated the C element interface according to the C++ methods provided in `t8_element_cxx.hxx`.
Furthermore, I rearranged the order of the rouines to match the `t8_element_cxx.hxx` header file.
This makes finding and comparing the matching routines easier.

Extending C element interface.

---

src/t8_cmesh/t8_cmesh.c

Removed an old code block that was commented out years ago.

remove deprecated code block

---

src/t8_schemes/t8_default/t8_default_pyramid/t8_default_pyramid_cxx.cxx
src/t8_schemes/t8_default/t8_default_pyramid/t8_default_pyramid_cxx.hxx
src/t8_schemes/t8_default/t8_default_pyramid/t8_dpyramid_bits.c
src/t8_schemes/t8_default/t8_default_pyramid/t8_dpyramid_bits.h

Added doxygen for some pyramid-functions and implemented improved version of some pyramid-functions

Enhance pyramid element

---

test/t8_schemes/t8_test_find_parent.cxx

Reduce the maximal level in the parent test to reduce the runtime for the tests

Reduce maxlvl in t8_test_find_parent

---

README.md

Update publications in README

---

doc/mainpage.dox

Just updated the links. Nothing serious.

Updating links in doxygen landing page.

---

benchmarks/time_forest_partition.cxx

Closes #315 
I removed the short option since i could not see a better alternative.
This should be reviewed by @sandro-elsweijer  since he wrote the option in the first place.
Are there any scripts that should be adjusted?

Fix issue 315

---

.github/workflows/add_release_documentation.yml
.github/workflows/update_documentation.yml

automate documentation upload to website

---

config/t8_vtk.m4

Added another library to make it compile with VTK 9.2.

---

.gitignore

Removed config directory from gitignore, because there are important files in it

Removed config directory from gitignore

---

config/t8_occ.m4

Added a library for linking with older occ versions

Add missing library for older OCC Versions

---

test/t8_schemes/t8_gtest_init_linear_id.cxx

Found some minor coding guideline violations in a test and corrected them. 

Updated class parameters to coding guideline, one line per variable

---

.gitignore

Added five new files to gitignore.

Added files to `.gitignore` which are generated via `./bootstrap`.

---

src/t8_geometry/t8_geometry_implementations/t8_geometry_occ.cxx

Added more information about how to fix a certain error while reading brep files.

Added more information to error message

---

test/t8_cmesh/t8_test_cmesh_readmshfile.cxx

Update msh 4 comment

---

src/t8_element_cxx.hxx

Based on the comments in #365 we improved the documentation of the `t8_element_tree_face` and `t8_element_is_root_boundary` functions.

Improve documentation for element tree boundary functions

---

src/t8_forest/t8_forest_cxx.cxx

There was a comment left stating that the check does not work for quads, but it does now.
Finally closes #268 

Clean up point inside check

---

src/t8_element_c_interface.cxx
src/t8_element_c_interface.h

Minor fix. Might fix the issue: https://github.com/DLR-AMR/t8code/issues/377

Add const in signature of t8_element_num_corners in header file

---

src/t8_cmesh/t8_cmesh_occ.cxx
src/t8_cmesh/t8_cmesh_readmshfile.cxx
test/t8_geometry/t8_gtest_geometry_occ.cxx

These array initializations were not exactly pretty.

Prettify array initializations

---

doc/author_becker.txt
src/t8_cmesh/t8_cmesh_examples.c

Fix issue #311

---

pull_request_template.md

Removed the line 
"- [ ] Testing of this template: If you feel something is missing from this list, contact the developers"
from the PR template.

Removing testing line from PR template.

---

example/geometry/t8_example_geometries.cxx

The new example uses the cylinder and sincos geometries.

Add a new geometry example using different geoms in the same mesh.

---

configure.ac
tutorials/Makefile.am

Fix issue 383

---

tutorials/Makefile.am
tutorials/general/t8_step6.h
tutorials/general/t8_step6_main.cxx
tutorials/general/t8_step6_stencil.cxx

Added another tutorial step. The wiki page can be found in https://github.com/DLR-AMR/t8code/wiki/Step-6-Computing-stencils .

Adding step6 tutorial.

---

scripts/find_all_source_files.scp
tutorials/features/t8_features_curved_meshes.cxx
tutorials/general/t8_step6_stencil.cxx

I updated the indent-script to check the files in the tutorial-directory and indented the files that were previously missed.

Update indent script

---

scripts/find_all_source_files.scp
tutorials/features/t8_features_curved_meshes.cxx
tutorials/general/t8_step6_stencil.cxx

Reverts DLR-AMR/t8code#440
the indent pipeline fails on main after this PR.
Must be resolved before merging.

Revert "Update indent script"

---

scripts/find_all_source_files.scp
scripts/indent_all_files.scp
src/t8_forest/t8_forest_ghost.cxx
tutorials/features/t8_features_curved_meshes.cxx
tutorials/general/t8_step6_stencil.cxx
tutorials/general/t8_tutorial_search.cxx

Reopening of PR #440 . New files were added into the tutorials folder, which is why it failed on the main-branch. 

Updated all new tutorials

---

.github/workflows/add_release_documentation.yml

Updates to the newest version of the pr workflow and deletes merged branch automatically

Update pr workflow

---

src/t8_vec.c
src/t8_vec.h
test/t8_gtest_vec.cxx

Added new function Y = a*X and respective test. Also updated `t8_vec.c` coding guideline.

Feature vec_axy

---

src/t8_eclass.c
src/t8_eclass.h

In some cases an edge enumeration of the coarse mesh cells is required.
These are so far only required for HEX and QUAD and are already defined but not implemented.

Edge enumeration for coarse mesh cells 

---

src/t8_cmesh/t8_cmesh_readmshfile.cxx
src/t8_cmesh/t8_cmesh_triangle.c
src/t8_windows.h

t8code is already set up to be portable to many other architectures thanks to the (mostly) rigorous use of standardized C/C++ code. For building t8code on 64-bit Windows systems via MinGW, there are two small exceptions: the functions `getline` and `strsep` are not part of the C standard, and they are not included in MinGW, thus compilation (or linking) fails on MinGW-based Windows systems.
This PR remedies this by providing an implementation for `getline` (based on public domain code) and `strsep` (own implementation) and includes them in the relevant source files of t8code. The inclusion of those files is guarded by a Windows-specific preprocessor directive, such that non-Windows platforms are not affected at all.
With this PR, it will be possible to, …

Allow building t8code for Windows (x86_64)

---

test/Makefile.am

Removed two lines in a Makefile.am. Nothing serious.

Removed superfluous Makfile operations.

---

src/t8.h
test/t8_geometry/t8_gtest_geometry_occ.cxx

Introduce a precision for t8code.

t8 precision

---

doc/author_hergl.txt

Added BSD Statement

---

tutorials/README.md

Added link to tutorial step 6 to README
Closes #505

Fix Issue505 - README

---

tutorials/general/t8_step0_helloworld.c
tutorials/general/t8_step1_coarsemesh.c
tutorials/general/t8_step2_uniform_forest.cxx

Closes #511 
Added comments about includes in tutorials 0-2. 

Improve tutorial documentation

---

README.md

Updates to the README regarding new publications.
- Added t8code papers to paper list
- Added a new list containing the theses written about t8code
- Added link to overview paper as entry point
- Fix doxygen path
Closes #523 

Update references in README

---

src/t8_schemes/t8_default/Makefile.am
src/t8_schemes/t8_default/t8_default_hex/t8_default_hex_cxx.cxx
src/t8_schemes/t8_default/t8_default_hex/t8_default_hex_cxx.hxx
src/t8_schemes/t8_default/t8_default_hex/t8_dhex.h
src/t8_schemes/t8_default/t8_default_hex/t8_dhex_bits.c
src/t8_schemes/t8_default/t8_default_hex/t8_dhex_bits.h
src/t8_schemes/t8_default/t8_default_line/t8_default_line_cxx.cxx
src/t8_schemes/t8_default/t8_default_line/t8_dline_bits.c
src/t8_schemes/t8_default/t8_default_line/t8_dline_bits.h
src/t8_schemes/t8_default/t8_default_prism/t8_default_prism_cxx.cxx
src/t8_schemes/t8_default/t8_default_prism/t8_dprism_bits.c
src/t8_schemes/t8_default/t8_default_prism/t8_dprism_bits.h
src/t8_schemes/t8_default/t8_default_pyramid/t8_default_pyramid_cxx.cxx
src/t8_schemes/t8_default/t8_default_pyramid/t8_dpyramid_bits.c
src/t8_schemes/t8_default/t8_default_pyramid/t8_dpyramid_bits.h
src/t8_schemes/t8_default/t8_default_quad/t8_default_quad_cxx.cxx
src/t8_schemes/t8_default/t8_default_quad/t8_default_quad_cxx.hxx
src/t8_schemes/t8_default/t8_default_quad/t8_dquad.h
src/t8_schemes/t8_default/t8_default_quad/t8_dquad_bits.c
src/t8_schemes/t8_default/t8_default_quad/t8_dquad_bits.h
src/t8_schemes/t8_default/t8_default_tet/t8_default_tet_cxx.cxx
src/t8_schemes/t8_default/t8_default_tet/t8_dtet_bits.h
src/t8_schemes/t8_default/t8_default_tet/t8_dtri_to_dtet.h
src/t8_schemes/t8_default/t8_default_tri/t8_default_tri_cxx.cxx
src/t8_schemes/t8_default/t8_default_tri/t8_dtri_bits.c
src/t8_schemes/t8_default/t8_default_tri/t8_dtri_bits.h
src/t8_schemes/t8_default/t8_default_vertex/t8_default_vertex_cxx.cxx
src/t8_schemes/t8_default/t8_default_vertex/t8_dvertex_bits.c
src/t8_schemes/t8_default/t8_default_vertex/t8_dvertex_bits.h

The implementation of the actual element ref coord functions. The function gets a set of reference coordinates inside an element $[0, 1]^d$ and maps these coordinates to the reference coordinates of the tree $[0, 1]^d$, regarding the anchor coordinate, level and orientation. This way, we can evaluate the geometry of arbitrary points inside an element. Before, we could only evaluate the vertices of the elements.
If the Pull request introduces code that is not covered by the github action (for example coupling with a new …

Feature puma patches [3/x] add element ref coords implementation

---

scripts/check_if_all_files_indented.scp
scripts/check_if_file_indented.scp
scripts/find_all_source_files.scp
scripts/indent_all_files.scp

This PR adds the possibility to run all intend scripts from the repo root directory. So, instead of doing this
```
cd scripts/
./indent_all_files.scp
cd ..
```
you now can just do this
```
./scripts/indent_all_files.scp
```
Awesome, right?! Makes life so much more comfortable ...
Closes https://github.com/DLR-AMR/t8code/issues/552.

Make indent scripts runnable from repo root directory.

---

README.md

Update README.md - Reference setup to Wiki

---

CITATION.cff
test/t8_gtest_version.cxx

New version 1.3.0

---

src/t8_vtk/t8_vtk_reader.cxx

fix vtk-warnings

---

README.md

Update status badges in README.md

---

src/t8_forest/t8_forest_general.h
src/t8_forest/t8_forest_ghost.cxx

Fix some typos

---

scripts/find_all_source_files.scp
scripts/indent_all_files.scp

Let the indent script also run over benchmarking files

---

src/t8_cmesh/t8_cmesh_examples.c

Found orientation-errors and fixed it. 

Fix the orientation of this example

---

src/t8_cmesh/t8_cmesh_examples.c

Fix orientation in cmesh-generator. 

Fix orientation pad

---

src/t8_cmesh/t8_cmesh_examples.c

Fix orientation

---

README.md

Title says it all. I added this note considering the [Helmholtz Incubator Software Award 2023](https://wiki.dlr.de/pages/viewpage.action?pageId=564241334) so that the jury sees that there is an ecosystem developing around t8code.

Update README with a note on the Julia wrapper.

---

src/Makefile.am

Fix a typo

---

example/geometry/t8_example_geometries.cxx
scripts/t8indent_custom_datatypes.txt
src/t8_geometry/t8_geometry_implementations/t8_geometry_occ.cxx

Add occ datatypes to custom datatypes

---

test/t8_gtest_eclass.cxx

Delete an INDENT-ON/OFF

---

src/t8_data/t8_shmem.c
src/t8_data/t8_shmem.h

Update indentation src-t8_data

---

src/t8_schemes/t8_default/t8_default_line/t8_default_line_cxx.cxx
src/t8_schemes/t8_default/t8_default_line/t8_dline_bits.c

Update indentation scheme-default_line

---

src/t8_schemes/t8_default/t8_default_quad/t8_default_quad.h
src/t8_schemes/t8_default/t8_default_quad/t8_default_quad_cxx.cxx

Update indentation schemes-default_quad

---

src/t8_schemes/t8_default/t8_default_vertex/t8_default_vertex_cxx.cxx

Update indentation schemes-default_vertex

---

test/t8_data/t8_gtest_shmem.cxx

Update test t8 data

---

src/t8.h
src/t8_cmesh.h
src/t8_cmesh_readmshfile.h
src/t8_eclass.c
src/t8_element_c_interface.h

Update src directory files

---

example/forest/t8_test_face_iterate.cxx
example/forest/t8_test_ghost.cxx
example/forest/t8_test_ghost_large_level_diff.cxx

Update example forest

---

tutorials/features/t8_features_curved_meshes.cxx
tutorials/general/t8_tutorial_build_cmesh.cxx

Update indentation tutorial

---

example/cmesh/t8_cmesh_create_partitioned.cxx
example/cmesh/t8_cmesh_set_join_by_vertices.cxx

Update indentation example_cmesh

---

example/forest/t8_test_face_iterate.cxx

Removed stray #

---

CITATION.cff
test/t8_gtest_version.cxx

New version 1.5.0

---

.typos.toml

Exclude logo from typo check

---

src/t8_geometry/t8_geometry_helpers.c

Delete old code, indented comment

Fix bugged compilation in puma_patches

---

.github/workflows/update_documentation.yml

Fix documentation CI

---

.github/workflows/update_documentation.yml

The PR reverts the failing of a github action. 

Revert "Fix documentation CI"

---

.github/workflows/update_documentation.yml

NEW: Tested before merging, see here:
[It can skip!](https://github.com/sandro-elsweijer/t8code/actions/runs/6160037529/job/16716073325)
[It can push!](https://github.com/sandro-elsweijer/t8code/actions/runs/6160116593/job/16716799712)
WHAT AN ACHIEVEMENT!

Fix documentation - now for real

---

src/t8_geometry/t8_geometry_implementations/t8_geometry_analytic.hxx
src/t8_geometry/t8_geometry_implementations/t8_geometry_linear.h
src/t8_geometry/t8_geometry_implementations/t8_geometry_linear.hxx
src/t8_geometry/t8_geometry_implementations/t8_geometry_linear_axis_aligned.h
src/t8_geometry/t8_geometry_implementations/t8_geometry_linear_axis_aligned.hxx
src/t8_geometry/t8_geometry_implementations/t8_geometry_occ.h
src/t8_geometry/t8_geometry_implementations/t8_geometry_occ.hxx
src/t8_geometry/t8_geometry_implementations/t8_geometry_zero.hxx

Improve the docstrings of geometry implementations

---

.github/workflows/check_indentation.yml
example/geometry/t8_example_geometries.cxx
scripts/check_if_file_indented.scp
scripts/t8indent

Also fixed the CI script to version 17.0.1.

Update clang-format to v17.0.1.

---

src/t8_geometry/t8_geometry_implementations/t8_geometry_examples.cxx
src/t8_geometry/t8_geometry_implementations/t8_geometry_examples.hxx

Convert squared disk cmesh example to batched version.

---

benchmarks/time_partition.cxx
src/t8_schemes/t8_default/t8_default_line/t8_default_line_cxx.cxx

Fixed spell errors raised by `typos-cli 1.16.17`.

---

.github/workflows/mattermost.yml

Feature ci mattermost messages test

---

.github/workflows/mattermost.yml

Revert "Feature ci mattermost messages"

---

src/t8_cmesh.h

This Todo does not refer to a function anymore.

---

example/forest/t8_test_ghost.cxx

Gave the adapt function a more explaining name

---

src/t8_forest/t8_forest_io.h
src/t8_forest/t8_forest_profiling.h

deleted cmesh.h from the header files

delete header functions

---

src/t8_cmesh/t8_cmesh_examples.c
src/t8_cmesh/t8_cmesh_examples.h

Remove todo

---

example/advect/t8_advection.cxx
scripts/check_if_file_indented.scp
scripts/t8indent
src/t8_forest/t8_forest_io.h

Besides that I put the required clang format version into variables. So that upates will be easier and less error prone in the future.
Addtionally, I applied the indent script which found two not properly indented files.

Update help message requiring specific clang format version.

---

test/t8_gtest_custom_assertion.hxx

Add include_guards

---

src/t8_schemes/t8_default/t8_default_prism/t8_default_prism_cxx.cxx
src/t8_schemes/t8_default/t8_default_prism/t8_dprism_bits.c
src/t8_schemes/t8_default/t8_default_prism/t8_dprism_bits.h

Cleaned up the code, deleted an obsolete function. 

Fix prism extrude face return value

---

src/t8_cmesh/t8_cmesh_offset.c
src/t8_cmesh/t8_cmesh_offset.h
src/t8_forest/t8_forest_partition.cxx

Added an option to hand over a starting point to the binary search in t8-cmesh_offset

Enhance t8 cmesh offset

---

tutorials/general/t8_step7_interpolation.cxx

Add preamble and file description

---

test/t8_schemes/t8_gtest_dfs_base.hxx
test/t8_schemes/t8_gtest_equal.cxx

Acutally use the check_element function for existing tests.

Fix interface

---

CITATION.cff
test/t8_gtest_version.cxx

Updated citation and test files to new patch release v1.6.1.

---

.github/workflows/check_indentation.yml

Use the actual name of the error output that is produced for uploading

Correct path for upload of error log

---

test/Makefile.am
test/t8_schemes/t8_gtest_child_parent_face.cxx

Introduce test for face relation of parent and child

---

src/t8_vec.h
test/t8_gtest_custom_assertion.hxx
test/t8_gtest_vec.cxx

Will make testing vectors easier for upcoming tests

Introduce a new Function that checks for equality for 3D vecs

---

src/t8_forest/t8_forest.c

Removed and simplified some unused stuff

Clean up some stuff

---

src/CMakeLists.txt

CMake fix for debug mode

---

src/t8_fortran_interface/t8_fortran_interface.c
src/t8_fortran_interface/t8_fortran_interface.h
src/t8_fortran_interface/t8_mo_fortran_interface.f90

- t8_fortran_cmesh_commit Wrapper ergänzt um Pointer zu dereferenzieren
- t8_fortran_geometry_linear_new_f & t8_fortran_cmesh_register_geometry_f: Rückgabewerte waren vertauscht
- Diverse Parametertypen verändert
- t8_cmesh_set_join_by_vertices ins Interface übernommen.

Feature fortran wrapper: Änderungen am Fortran-Interface und C-Wrapper

---

example/cmesh/t8_cmesh_hypercube_pad.cxx
src/t8_geometry/t8_geometry_helpers.c
src/t8_geometry/t8_geometry_implementations/t8_geometry_linear_axis_aligned.cxx
test/t8_geometry/t8_geometry_implementations/t8_gtest_geometry_linear.cxx
test/t8_geometry/t8_gtest_geometry_macros.hxx
test/t8_geometry/t8_gtest_point_inside.cxx

Revert "update number of the corner of the second vertex"

---

test/t8_cmesh_generator/t8_cmesh_parametrized_examples/t8_cmesh_params.hxx
test/t8_forest/t8_gtest_forest_commit.cxx

Hopefully this one gets it down to less than 90 min

reduce test size

---

example/cmesh/t8_cmesh_hypercube_pad.cxx
src/t8_geometry/t8_geometry_helpers.c
src/t8_geometry/t8_geometry_implementations/t8_geometry_linear_axis_aligned.cxx
test/Makefile.am
test/t8_geometry/t8_geometry_implementations/t8_gtest_geometry_lagrange.cxx
test/t8_geometry/t8_geometry_implementations/t8_gtest_geometry_linear.cxx
test/t8_geometry/t8_gtest_geometry_macros.hxx
test/t8_geometry/t8_gtest_point_inside.cxx

It was apparently not a bitflip ...
Reverts DLR-AMR/t8code#983

Revert "Revert "Revert "update number of the corner of the second vertex"""

---

tutorials/general/t8_step7_interpolation.cxx

I found and fixed some typos in the comments of `t8_step7_interpolation.cxx`.

Fix some typos in t8_step7_interpolation.cxx

---

.github/workflows/check_indentation.yml
.github/workflows/mattermost.yml
.github/workflows/spell_check.yml
.github/workflows/tests_sc_p4est.yml
.github/workflows/tests_t8code_linkage_parallel_debug.yml
.github/workflows/tests_t8code_linkage_parallel_release.yml
.github/workflows/tests_t8code_parallel.yml
.github/workflows/tests_t8code_serial.yml

Add the mainpp branch to all important CI runs.

Add mainpp to CI runs

---

test/t8_gtest_version.cxx

Change version number test

---

CITATION.cff
configure.ac

Minor update of 2.0.0 alpha
Changes in author file and bugreport

New version 2.0.0 alpha

---

INSTALL
README.md

Feature update readme

---

test/Makefile.am

The headers of the test files were added to the Makefile, so that the tarball can be build

Add headers to testfile

---

src/t8_fortran_interface/t8_fortran_interface.c
src/t8_fortran_interface/t8_fortran_interface.h
src/t8_fortran_interface/t8_mo_fortran_interface.f90

Fortran interface: Added t8_cmesh_set_join_by_vertices

---

example/advect/t8_advection.cxx

Change the abbreviation to match the long version

Adapt short cli argument of advection solver to cad rename

---

.github/workflows/mattermost.yml

Look inside the Mattermost GitHub channel to see the fix in action

Fix mattermost bot

---

CITATION.cff

Typo in CITATION.cff

---

CITATION.cff

Add ORCID of Florian

---

src/CMakeLists.txt

cmake: filename has changed from .c to .cxx

---

.github/workflows/tests_t8code_serial.yml
.github/workflows/update_documentation.yml

Add apt-get update and upgrade to update_documentation action.
The action was failing due to the doxygen package not being installed properly.
This may fix it.

Add apt-get update and upgrade to update_documentation action

---

.github/workflows/add_release_documentation.yml
.github/workflows/check_indentation.yml
.github/workflows/ci_playground.yml
.github/workflows/test_tarball.yml
.github/workflows/tests_sc_p4est.yml
.github/workflows/tests_t8code_linkage_parallel_debug.yml
.github/workflows/tests_t8code_linkage_parallel_release.yml
.github/workflows/tests_t8code_parallel.yml
.github/workflows/tests_t8code_serial.yml
.github/workflows/update_documentation.yml

Add sudo apt-get update && sudo apt-get upgrade -y to all actions
Note: we require fetch-depth: 0 in our workflow since it ensure that the t8code version number is generated properly

Add sudo apt-get update && sudo apt-get upgrade -y to all actions

---

src/t8_cmesh/t8_cmesh_offset.c

Add assertion that fails if offset array is just filled with -1

---

src/t8_cmesh/t8_cmesh_copy.c
src/t8_cmesh/t8_cmesh_trees.c
test/t8_cmesh/t8_gtest_cmesh_copy.cxx

Fixes most of the problems that made the cmesh_copy_test fail.

Fix most of cmesh_copy

---

src/t8_cmesh.h
src/t8_forest/t8_forest_general.h
src/t8_forest/t8_forest_private.h
src/t8_geometry/t8_geometry_helpers.c
src/t8_geometry/t8_geometry_implementations/t8_geometry_examples.hxx

Correct typos in main that make the spell checker fail

Correct typos

---

example/CMakeLists.txt

This PR fixes the issue  #1121.

Fix: building examples with the CMake build system

---

src/t8_cmesh/t8_cmesh_partition.cxx
src/t8_cmesh/t8_cmesh_readmshfile.cxx

Scanned t8_cmesh_readmshfile to add more const

More const in t8_cmesh_readmshfile

---

src/t8_cmesh/t8_cmesh_save.cxx

More const parameters in t8_cmesh_save

more const in cmesh_save

---

src/t8_cmesh.h
src/t8_cmesh/t8_cmesh.cxx
src/t8_cmesh/t8_cmesh_examples.cxx
src/t8_cmesh/t8_cmesh_geometry.cxx
src/t8_geometry/t8_geometry_handler.cxx
src/t8_geometry/t8_geometry_handler.hxx

I basically just switched from a pointer-pointer to just a pointer. I see no reason why an application should manage a reference to the pointer of a geometry. Besides, I'm having troubles with the garbage collector in Julia wiping the reference to the geometry away.

Simplified C interface for registering geometries in cmeshes.

---

CMakeLists.txt
src/CMakeLists.txt

Add CMake option to enable less tests.

---

.github/workflows/tests_sc_p4est.yml
.github/workflows/tests_t8code_linkage_parallel_debug.yml
.github/workflows/tests_t8code_linkage_parallel_release.yml
.github/workflows/tests_t8code_parallel.yml
.github/workflows/tests_t8code_serial.yml

Fix CI with occ

---

cmake/GitProjectVersion.cmake
src/CMakeLists.txt
src/t8_version.c

Fixed failing version test with CMake.

---

src/t8_forest/t8_forest_general.h
tutorials/general/t8_step6_stencil.cxx

Fixed memory leak in tutorial step 06 and added documentation.

---

src/t8_geometry/t8_geometry_helpers.c
src/t8_schemes/t8_default/t8_default_vertex/t8_dvertex_bits.c

replace abs by fabs

---

CONTRIBUTING.md

add link to coding guidelines in contributing file

---

INSTALL

This PR adds basic instruction to compile t8code using the CMake build system in the INSTALL file.
Closes #1168

Added CMake installation instructions in the INSTALL file

---

test/CMakeLists.txt
test/Makefile.am
test/t8_geometry/t8_gtest_geometry_triangular_interpolation.cxx

Implement 2 basic tests for the t8_geom_triangular_interpolation function.
We test whether the corner interpolation coordinates are properly mapped to the corners.
The test suit could still be extended but i believe it is good to merge this first version.

Test t8_geom_triangular_interpolation

---

scripts/indent_all_files.scp

Add api folder to indent all files script

---

test/t8_cmesh/t8_gtest_hypercube.cxx
test/t8_forest/t8_gtest_element_volume.cxx
test/t8_forest/t8_gtest_forest_commit.cxx

Minor typo fixes and enhancements

---

src/t8_data/t8_data_handler.hxx
src/t8_data/t8_data_handler_base.hxx
src/t8_data/t8_data_packs/t8_enlarged_stdtypes.hxx
test/t8_data/t8_gtest_data_handler.cxx
test/t8_data/t8_pseudo_trees.hxx

Further optimization for the user-data interface

Pack opimization

---

doc/author_albers.txt
tutorials/features/t8_features_curved_meshes.cxx

The wiki page and the tutorial did not line up (Closes #1252  ) The changes clean that up. 
There was also a wrong Error message, suggesting the `-s` option which doesn't exist. 
Together with the PR, I also changed the Wiki page [Feature Curved meshes](https://github.com/DLR-AMR/t8code/wiki/Feature---Curved-meshes), so please have a look there too. 

Fix issue 1252

---

src/t8_forest/t8_forest_iterate.cxx

Fix an assertion

---

example/IO/forest/netcdf/t8_write_forest_netcdf.cxx
example/advect/t8_advection.cxx
example/cmesh/t8_cmesh_hypercube_pad.cxx
example/forest/t8_face_neighbor.cxx
example/remove/t8_example_empty_trees.cxx
src/t8_geometry/t8_geometry_implementations/t8_geometry_analytic.hxx
src/t8_vtk/t8_vtk_write_ASCII.cxx
test/t8_cmesh/t8_gtest_cmesh_set_partition_offsets.cxx
test/t8_schemes/t8_gtest_boundary_extrude.cxx
test/t8_schemes/t8_gtest_child_parent_face.cxx
test/t8_schemes/t8_gtest_equal.cxx
test/t8_schemes/t8_gtest_face_descendant.cxx
test/t8_schemes/t8_gtest_find_parent.cxx
test/t8_schemes/t8_gtest_nca.cxx
test/t8_schemes/t8_gtest_pack_unpack.cxx
tutorials/general/t8_step1_coarsemesh.cxx
tutorials/general/t8_step2_uniform_forest.cxx
tutorials/general/t8_step3_adapt_forest.cxx
tutorials/general/t8_tutorial_search.cxx

Fix various warnings

---

example/version/t8_version.cxx
src/t8_cmesh/t8_cmesh_readmshfile.cxx
src/t8_geometry/t8_geometry_implementations/t8_geometry_examples.cxx

Main was failing due to some spelling-errors. This PR fixes it. 

Fix spelling-errors

---

doc/author_fussbroich.txt

Correct mail address

---

src/t8_data/t8_element_array_iterator.hxx
src/t8_forest/t8_forest.cxx

I missed two names in my review. This updates the names to our coding-guidelines. 

Update functionname to naming scheme

---

.gitignore

Add ctest Testing folder to .gitignore

---

pull_request_template.md

Add tag labels to pr template

---

src/t8_schemes/t8_default/t8_default_line/t8_dline.h

In p4est the order in a `p4est_quadrant` is coords then level. To be compatible in all directions the order is adjusted here. 

Switch the order of coords and level

---

test/t8_forest/t8_gtest_balance.cxx
test/t8_forest/t8_gtest_element_volume.cxx
test/t8_forest/t8_gtest_find_owner.cxx
test/t8_forest/t8_gtest_forest_face_normal.cxx
test/t8_forest/t8_gtest_half_neighbors.cxx
test/t8_forest/t8_gtest_partition_data.cxx
test/t8_forest/t8_gtest_search.cxx
test/t8_gtest_schemes.hxx
test/t8_schemes/t8_gtest_boundary_extrude.cxx
test/t8_schemes/t8_gtest_child_parent_face.cxx
test/t8_schemes/t8_gtest_face_descendant.cxx
test/t8_schemes/t8_gtest_face_neigh.cxx

Add the default scheme macro again to test the face functions just for the default scheme. This change will be reverted with PR #1345 

Add temporay default scheme macro

---

test/CMakeLists.txt
test/t8_schemes/t8_gtest_input_equal_output.cxx

Test to check whether the input element is overwritten when the input is equal the output[0]. 

Test input = output

---

README.md

This PR adds an entry for the JOSS paper of t8code in the readme.

Adding link to JOSS paper in README.md.

---

AUTHORS
CITATION.cff

correct typo in name

---

.github/workflows/build_cmake_tarball.yml
.github/workflows/check_indentation.yml
.github/workflows/mattermost_issue.yml
.github/workflows/mattermost_pull_request.yml

ubuntu-20.04 won't be supported for to long. This branch updates all workflow that used 20.04 to 22.04. 

Update all github-runners to ubuntu-22.04

---

tutorials/general/t8_step1_coarsemesh.cxx
tutorials/general/t8_step2_uniform_forest.cxx
tutorials/general/t8_step3_adapt_forest.cxx
tutorials/general/t8_step6_stencil.cxx
tutorials/general/t8_step7_interpolation.cxx
tutorials/general/t8_tutorial_build_cmesh.cxx
tutorials/general/t8_tutorial_search.cxx

- Adapt comments to get proper doxygen comments.
- Typos and copy & paste errors
- Use modern C++ for all struct definitions (previously used inconsistently).
- Use adapt_data-> consistently instead of (*adapt_data). .

Improvements to the tutorials

---

src/t8_cmesh.h

Closes #87
The Issues has been opened some time ago, there was no urge to implement the function yet, so we can delete it. 

Delete obsolete function

---

example/IO/cmesh/gmsh/t8_load_and_refine_square_w_hole.cxx
src/t8_cmesh/t8_cmesh.cxx
src/t8_cmesh/t8_cmesh_examples.cxx
src/t8_forest/t8_forest.cxx
src/t8_geometry/t8_geometry_helpers.c
src/t8_geometry/t8_geometry_implementations/t8_geometry_examples.cxx
src/t8_types/t8_vec.cxx
src/t8_types/t8_vec.h
test/t8_gtest_eclass.cxx
test/t8_schemes/t8_gtest_element_ref_coords.cxx
tutorials/general/t8_step3_adapt_forest.cxx

We decided to not append c-interface function with a _c_interface suffix, but to clearly seperate the functions in the headers. 
This PR fixes this for the vector implementation. 

Update vec c interface

---

src/t8_forest/t8_forest_ghost.cxx

Fixes a ghost warning which causes my build to fail.
Possibly it also fixes a memory leak.

Fix ghost warning

---

README.md

- Problem was, that `make target` is case sensitive but the target is called `Doxygen` instead of `doxygen`. 
- Maintainability is increased because the instructions from the wiki are no longer repeated.

Adapt documentation paragraph in README

---

test/t8_forest_incomplete/t8_gtest_iterate_replace.cxx

- 2 test runs for all test levels as something different is tested in the second run of the implemented test.
- Decrease level of uniform forest for test level 1.

Adapt iterate replace test for test levels 1 and 2

---

NEWS.md
src/t8_forest/t8_forest.cxx
src/t8_schemes/t8_default/t8_default_hex/t8_default_hex.cxx
src/t8_schemes/t8_default/t8_default_hex/t8_default_hex.hxx
src/t8_schemes/t8_default/t8_default_line/t8_default_line.cxx
src/t8_schemes/t8_default/t8_default_line/t8_default_line.hxx
src/t8_schemes/t8_default/t8_default_prism/t8_default_prism.cxx
src/t8_schemes/t8_default/t8_default_prism/t8_default_prism.hxx
src/t8_schemes/t8_default/t8_default_pyramid/t8_default_pyramid.cxx
src/t8_schemes/t8_default/t8_default_pyramid/t8_default_pyramid.hxx
src/t8_schemes/t8_default/t8_default_quad/t8_default_quad.cxx
src/t8_schemes/t8_default/t8_default_quad/t8_default_quad.hxx
src/t8_schemes/t8_default/t8_default_tet/t8_default_tet.cxx
src/t8_schemes/t8_default/t8_default_tet/t8_default_tet.hxx
src/t8_schemes/t8_default/t8_default_tri/t8_default_tri.cxx
src/t8_schemes/t8_default/t8_default_tri/t8_default_tri.hxx
src/t8_schemes/t8_default/t8_default_vertex/t8_default_vertex.cxx
src/t8_schemes/t8_default/t8_default_vertex/t8_default_vertex.hxx
src/t8_schemes/t8_scheme.cxx
src/t8_schemes/t8_scheme.h
src/t8_schemes/t8_scheme.hxx
src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
test/t8_forest/t8_gtest_find_owner.cxx
test/t8_schemes/t8_gtest_bfs_base.hxx
test/t8_schemes/t8_gtest_descendant.cxx
test/t8_schemes/t8_gtest_dfs_base.hxx
test/t8_schemes/t8_gtest_face_neigh.cxx
test/t8_schemes/t8_gtest_get_linear_id.cxx
test/t8_schemes/t8_gtest_root.cxx
test/t8_schemes/t8_gtest_successor.cxx

In the function get_root nothing is returned, but the input element is set to root coordinates
Therefore this function should be renamed to a setter function. 

rename get_root -> set_to_root

---

scripts/check_macros.sh
scripts/pre-commit

Removes the macro checker from the pre-commit script, since it always fails for already existing macros. We can enable it when we removed the faulty macros.
Furthermore, it makes the macro checker less verbose, since for many changes (especially merges with main), it produces so much output that indentation and spelling errors can hardly be found in the output.

Remove macro checker

---

test/t8_schemes/t8_gtest_face_corner.cxx

Replace T8_ENABLE_LESS_TEST by T8CODE_TEST_LEVEL in test/t8_schemes/t8_gtest_face_corner.cxx.

Bugfix: Replace T8_ENABLE_LESS_TEST by T8CODE_TEST_LEVEL 

---

src/t8_cmesh.h
src/t8_cmesh/t8_cmesh_types.h

Documentation: set join orientation

---

pull_request_template.md

Improvement: Remove inconsistent line from PR template

---

src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx

Enhancement: Align standalone to coding guidelines

---

tutorials/features/t8_features_curved_meshes_generate_cmesh_tet.geo
tutorials/features/t8_features_curved_meshes_generate_cmesh_tri.geo

The geo files in our curved mesh tutorial used `sqrt` instead of `Sqrt` and this lead to gmsh crashing.

Fix syntax in geo files

---

config/t8_fortran.m4
config/t8_include.m4
config/t8_mpi.m4
config/t8_netcdf.m4
config/t8_occ.m4
config/t8_vtk.m4
src/t8_vtk/t8_vtk_write_ASCII.hxx
src/t8_vtk/t8_vtk_writer.h
test/t8_gtest_netcdf_linkage.cxx
test/t8_gtest_occ_linkage.cxx
test/t8_gtest_vtk_linkage.cxx

Bugfix: Fix CI problem with documentation

---

src/t8_schemes/t8_default/t8_default_vertex/t8_default_vertex.cxx

The typos script found another typo. This PR fixes it. 

Improvement: Fix a typo

---

test/t8_forest/t8_gtest_element_volume.cxx
test/t8_forest/t8_gtest_forest_face_normal.cxx

With these includes we cannot link against an external sc. The CI change to catch this is getting its own PR

Fix some includes

---

test/t8_forest/t8_gtest_forest_face_normal.cxx
test/t8_gtest_schemes.hxx

Does not change anything, but these includes were not straightforward or outdated.

Fix some other includes

---

NEWS.md

Closes #1529 
Adds a paragraph to NEWS.md to describe the workflow. 

Documentation: Document issue wf

---

.github/workflows/move_card.yml
.github/workflows/quick_pr.yml

Handles creation of issues and moving of issue cards in projects for draft prs. 
Closes #1539 

Bugfix: Handle draft prs

---

README.md

Closes #1546
Added  AMR25 conference information to the global README.
Do you miss any information? Or is it even too long?

Add AMR25 conference information to README

---

.github/workflows/move_card.yml
.github/workflows/quick_pr.yml

Directly add a Issue created by a quick-PR to a project. 
Closes #1542 

Bugfix: Connect issue to project

---

scripts/pre-commit

Closes #1536
Addresses #1534. As outlined in the issue, the current version of `scripts/pre-commit` does not seem to work.
This PR fixes it again and makes sure to use absolute paths for calling `check_if_file_indented.sh` and `check_macros.sh`, such that linking the `pre-commit` script into `.git/hooks/` rather than copying should work too, as discussed in #1534.
If the Pull request introduces code that is not covered by the github action (for …

Bugfix: Fix wrong paths in pre-commit script

---

.github/ISSUE_TEMPLATE/bug_report.md

Closes #1550
Automatically set the type of the Issue, if the issue-template for bugs is used. 

Improvement: Add type for bug issue_template

---

.github/ISSUE_TEMPLATE/feature_request.md

Closes #1552
Automatically set the type of an Issue to feature if it is opened via the feature-issue-template. 

Improvement: Automatically set issue type to feature

---

.github/ISSUE_TEMPLATE/bug_report.md

Closes #1554
The added type created an error in the creation of the template

Bugfix: Issue Template

---

.github/ISSUE_TEMPLATE/feature_request.md

Bugfix: Error in feature Template

---

.github/workflows/issue_event_moves_card.yml
.github/workflows/pr_event_moves_card.yml

Closes #1564 
Use page cursors to get around the item limit set by gh. 
We allow a maximum of 100 iterations to prevent an endless loop if an error occurs. 

Bugfix: T8ddy learns how to use a page to iterate over all items in a project

---

src/t8_schemes/t8_default/t8_default_common/t8_default_common.hxx

Closes #1562 
Rename `ts_context` to `scheme_context` and update the documentation.

Improvement: Rename ts_context

---

CMakeLists.txt

Closes #1569
In most cases, the developers change this option to OFF. To reduce the number of options that has to be changed, it is nicer to have it as default value. 
This change could maybe be discussed as the option is also switched off for users where it may be good to also run the TPL tests.

Improvement: Change default value of T8CODE_BUILD_TPL_TESTS option to OFF

---

.github/workflows/move_card.yml

closes #1586 
In the regex search for [Cc]loses to allow for capital and lower letters. 
This PR should demonstrate its functionality. 

Bugfix: ignore the case for the letter "C" in "Closes"

---

test/t8_gtest_custom_assertion.hxx

Related to the error in PR #1524 and Issue #1528 
In this case Clang doesn't compile because the "return type 'testing::AssertionResult' is not a literal type". Therefore `constexpr` is removed here. 

Bugfix: constexpr error

---

.github/workflows/build_cmake_tarball.yml
.github/workflows/check_indentation.yml

Closes #1603
These package updates are unnecessary because clang-format is installed via pip. Denk doch jemand an die Umwelt!

Improvement: Remove package update in indent workflow

---

example/geometry/t8_example_geometries.cxx
src/CMakeLists.txt
src/t8_cmesh/t8_cmesh_cad.cxx
src/t8_cmesh/t8_cmesh_readmshfile.cxx
src/t8_geometry/t8_geometry_handler.cxx
src/t8_geometry/t8_geometry_implementations/t8_geometry_cad.cxx
src/t8_geometry/t8_geometry_implementations/t8_geometry_cad.h
src/t8_geometry/t8_geometry_implementations/t8_geometry_cad.hxx
test/t8_geometry/t8_gtest_geometry_handling.cxx
tutorials/features/t8_features_curved_meshes.cxx

Closes #1611 
Removes all T8_ENABLE_OCC flags in headers. 

Improvement: Get rid of T8_ENABLE_OCC in headers

---

README.md

Closes #1619
Removed conference information from README as the information is deprecated and the abstract submission deadline is over.

Improvement: Remove conference information from README 

---

src/t8_schemes/t8_default/t8_default_common/t8_default_common.hxx
src/t8_schemes/t8_default/t8_default_hex/t8_default_hex.hxx
src/t8_schemes/t8_default/t8_default_line/t8_default_line.hxx
src/t8_schemes/t8_default/t8_default_prism/t8_default_prism.hxx
src/t8_schemes/t8_default/t8_default_pyramid/t8_default_pyramid.hxx
src/t8_schemes/t8_default/t8_default_quad/t8_default_quad.hxx
src/t8_schemes/t8_default/t8_default_tet/t8_default_tet.hxx
src/t8_schemes/t8_default/t8_default_tri/t8_default_tri.hxx
src/t8_schemes/t8_default/t8_default_vertex/t8_default_vertex.hxx
src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx

Closes #1597
Some improvements I made while working on the multilevel scheme.

Scheme improvements

---

src/t8_cmesh/t8_cmesh_readmshfile.cxx

There was an error in the conversion tables for our msh to t8 node ordering which lead do tetrahedra getting negative volumes.

Bugfix: msh node conversion tables

---

src/t8_cmesh.hxx
test/CMakeLists.txt
test/t8_cmesh/t8_gtest_compute_first_element.cxx

Closes #1578 
Splits the uint64 into two int32_t, that are stored in a 64-bit uint.
Using that mpirank <= mpisize (we compute the last element of a process via mpirank + 1, so we actually reach mpisize with mpirank), we can formulate the computation in a way such that all intermediate results don't overflow. 
After review, the computation is now done by using:
`floor(ab/c) = floor(a/c)floor(b/c) + floor(a/c)(b%c) + (a%c) floor(b/c) +floor((a%c)(b%c))/c)`
with `b<=c`
If the Pull …

Feature: Implement computation of the first element of a process

---

src/CMakeLists.txt
src/t8_cmesh.hxx
src/t8_cmesh/t8_cmesh_vertex_connectivity/t8_cmesh_vertex_conn_vertex_to_tree.cxx
src/t8_cmesh/t8_cmesh_vertex_connectivity/t8_cmesh_vertex_conn_vertex_to_tree.hxx
src/t8_cmesh/t8_cmesh_vertex_connectivity/t8_cmesh_vertex_connectivity.cxx
src/t8_cmesh/t8_cmesh_vertex_connectivity/t8_cmesh_vertex_connectivity.h
src/t8_cmesh/t8_cmesh_vertex_connectivity/t8_cmesh_vertex_connectivity.hxx
src/t8_cmesh/t8_cmesh_vertex_connectivity/t8_cmesh_vertex_connectivity_types.hxx
test/t8_cmesh/t8_gtest_cmesh_vertex_conn.cxx

Closes #1623
Add to #960.
- We forgot to add the function t8_cmesh_vertex_conn_vertex_to_tree  that retrieves a list of all (tree vertex) pairs for a global vertex Id to the cmesh public interface.
I added the function now.
- The vertex connectivity headers were exposed in the public interface. 
I removed them

Feature: Add t8_cmesh_vertex_conn_vertex_to_tree to the cmesh interface and remove headers from public interface

---

.github/workflows/issue_event_moves_card.yml
.github/workflows/move_card.yml
.github/workflows/pr_event_moves_card.yml
.github/workflows/quick_pr.yml

Closes #1639
Added missing copyright information for issue board workflows. 

Other: Added missing copyright information for issue board workflows

---

NEWS.md

Closes #1533.
Added section for renamed macros (T8_WITH_ to T8_ENABLE_) to NEWS.md.

Other: Added section for renamed macros to NEWS.md

---

src/t8_types/t8_vec.hxx

Closes #1695
Fixed a typo in the documentation

Fix typo in documentation

---

.github/workflows/code_coverage.yml
.github/workflows/tests_cmake_preparation.yml
.github/workflows/tests_cmake_sc_p4est.yml
.github/workflows/tests_cmake_t8code.yml
.github/workflows/tests_cmake_t8code_api.yml
.github/workflows/tests_cmake_t8code_linkage.yml
.github/workflows/tests_cmake_t8code_w_shipped_submodules.yml
.github/workflows/tests_cmake_valgrind.yml

Closes #1704
Our CI runs keep failing with:
```bash
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/m/mesa/libegl-mesa0_23.2.1-1ubuntu3.1%7e22.04.3_amd64.deb  403  Forbidden [IP: 185.125.190.82 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/m/mesa/libgbm1_23.2.1-1ubuntu3.1%7e22.04.3_amd64.deb  403  Forbidden [IP: 185.125.190.82 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/m/mesa/libgl1-mesa-dri_23.2.1-1ubuntu3.1%7e22.04.3_amd64.deb  403  Forbidden [IP: 185.125.190.82 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/m/mesa/libglx-mesa0_23.2.1-1ubuntu3.1%7e22.04.3_amd64.deb  403  Forbidden [IP: 185.125.190.82 80]
E: Failed to fetch …
```

Fix: CI updates run into 403 error.

---

src/t8_schemes/t8_default/t8_default_tet/t8_dtet_connectivity.h

Documentation: t8_dtet_type_face_to_boundary

---

src/t8_cmesh/t8_cmesh_trees.cxx
src/t8_cmesh/t8_cmesh_vertex_connectivity/t8_cmesh_vertex_conn_tree_to_vertex.cxx
src/t8_geometry/t8_geometry_implementations/t8_geometry_examples.hxx
src/t8_schemes/t8_default/t8_default_line/t8_default_line.hxx
src/t8_schemes/t8_default/t8_default_quad/t8_default_quad.hxx
src/t8_schemes/t8_default/t8_default_tri/t8_default_tri.hxx
src/t8_types/t8_operators.hxx
src/t8_types/t8_type.hxx

Closes #1742
Fix all errors/warnings that are printed while generating the doxygen-documentation.
I figured along the line, that this will be a bigger task. To make it more digestible I will split the task into module-specific PRs. 
However, this can be merged. 

Documentation: Fix doxygen

---

src/CMakeLists.txt

Install vertex connectivity headers needed by t8_cmesh_types.h
Closes #1762 

Bugfix: Install vertex connectivity headers

---

src/t8_vtk.h
src/t8_vtk/t8_vtk_types.h
src/t8_vtk/t8_vtk_write_ASCII.cxx
src/t8_vtk/t8_vtk_write_ASCII.hxx
src/t8_vtk/t8_vtk_writer.cxx
src/t8_vtk/t8_vtk_writer.h
src/t8_vtk/t8_vtk_writer.hxx
src/t8_vtk/t8_vtk_writer_helper.hxx
src/t8_vtk/t8_with_vtk/t8_vtk_parallel.hxx
src/t8_vtk/t8_with_vtk/t8_vtk_polydata.hxx
src/t8_vtk/t8_with_vtk/t8_vtk_reader.cxx
src/t8_vtk/t8_with_vtk/t8_vtk_reader.hxx
src/t8_vtk/t8_with_vtk/t8_vtk_unstructured.hxx

Closes #1754 
Fixed all doxygen errors related to src/t8_vtk/* 

Documentation: Fix doxygen errors. 

---

NEWS.md
src/t8_cmesh/t8_cmesh_vertex_connectivity/t8_cmesh_vertex_conn_tree_to_vertex.hxx
tutorials/general/t8_step5_element_data.cxx
tutorials/general/t8_step5_element_data_c_interface.c

Improvement: Correct some small typos

---

.github/workflows/quick_pr.yml

Closes #1834
This change should prevent the quick_pr from failing for PRs that come from outside-contributors. With the changes it should work for forks, too. 

Improvement: Make quick_pr more robust. 

---

README.md

Closes #1840
Noticed the deprecated AMR25 information. 
Other than deleting it, we could replace the information with something like, We organized AMR25, which was a great event, or similar.

Other: Remove conference information from README

---

src/t8_schemes/t8_standalone/t8_standalone_elements.hxx
src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx

fixes doxygen for standalone scheme
Closes #1750

Doxumenation: fix doxygen errors in standalone

---

src/t8_data/t8_element_array_iterator.hxx
src/t8_data/t8_shmem.c
src/t8_schemes/t8_scheme.h
src/t8_types/t8_operators.hxx
src/t8_types/t8_type.hxx
src/t8_types/t8_vec.h
src/t8_types/t8_vec.hxx

Documentation: Fix docu t8 types

---

src/t8.h
src/t8_cmesh.h
src/t8_element.h
src/t8_element_shape.h
src/t8_mat.h
src/t8_netcdf.h
src/t8_version.h

Documentation: Fix doxygen errors in src

---

NEWS.md
src/t8_element_shape.h
src/t8_forest/t8_forest_adapt.cxx
src/t8_forest/t8_forest_adapt.h
test/t8_forest/t8_gtest_balance.cxx
test/t8_forest/t8_gtest_ghost_delete.cxx
test/t8_gtest_custom_assertion.hxx
test/t8_types/t8_gtest_type.cxx

Closes #1883
Fixed some typos i came across while working on the unstructured mesh interface. 

Documentation: Fix some typos
