src/t8_forest/t8_forest_ghost.cxx
src/t8_forest/t8_forest_iterate.cxx
src/t8_forest/t8_forest_iterate.h
test/Makefile.am
test/t8_test_search.cxx

We extend the forest_search with a set of queries and a query callback.
For all elements that match the element callback, the query callback is called with each active query.
Query for which this call returns 0 are deactivated for the next recursion step.
If all active queries return 0 on an element, the recursion does not continue.

Feature search with points

---

src/t8_forest/t8_forest_ghost.cxx
src/t8_forest/t8_forest_iterate.cxx
src/t8_forest/t8_forest_iterate.h
test/t8_test_search.cxx

The search callback gets as additional information
the index of the query in the global queries array.
This allows us easily to identify the current query.
An example usage would be to pass an array of lenght
number of queries as user pointer and store the matching
elements for each query and the correct position in
this array.

Add a query index to the search callback.

---

src/t8_cmesh.h
src/t8_cmesh/t8_cmesh.c
src/t8_cmesh/t8_cmesh_commit.c
src/t8_cmesh/t8_cmesh_trees.c
src/t8_cmesh/t8_cmesh_trees.h
test/Makefile.am
test/t8_test_cmesh_face_is_boundary.cxx

The cmesh gets a new function t8_cmesh_get_face_neighbor to gather face neighbor information from a local treeid.
We also add additional helper functions to check whether a local id is  a local tree or ghost.
We add tree_to_face encode and decode function to ease handling of the tree_to_face data (dual face and orientation).
We add  a test for the new t8_cmesh_get_face_neighbor function.
While testing we discovered an old bug in t8_cmesh_commit that computed wrong tree counts when the cmesh was build from stash with t8_cmesh_set_partition_range.
This bug is now fixed.

Feature cmesh face info getter

---

test/t8_test_bcast.c
test/t8_test_cmesh_copy.c
test/t8_test_cmesh_face_is_boundary.cxx
test/t8_test_cmesh_partition.cxx
test/t8_test_eclass.c
test/t8_test_element_count_leafs.cxx
test/t8_test_element_general_function.cxx
test/t8_test_find_owner.cxx
test/t8_test_find_parent.cpp
test/t8_test_forest_commit.cxx
test/t8_test_ghost_and_owner.cxx
test/t8_test_ghost_exchange.cxx
test/t8_test_half_neighbors.cxx
test/t8_test_hypercube.c
test/t8_test_search.cxx
test/t8_test_transform.cxx

The copyright statement in the tests wrongly
listed the university of Texas.
This was a copy-paste error.
We changed it now to list 'the developers'.

Fix copyright statement in tests.

---

src/t8_element_cxx.hxx
src/t8_schemes/t8_default/t8_default_common_cxx.cxx
src/t8_schemes/t8_default/t8_default_common_cxx.hxx

This function returns the number of siblings of
an element.
We add a default implementation that returns
2**dim. For pyramids we will have to implement
a standalone definition.

Add a num_siblings element function.

---

doc/author_boeing.txt
scripts/pre-commit
src/t8_cmesh/t8_cmesh_readmshfile.c
src/t8_cmesh_readmshfile.h

An error message will be thrown, if the provided msh-file has an incompatible MeshFormat number and therefore cannot be read by "t8_cmesh_readmshfile.c". Currently supported are msh-files of version 2 or lower.

Feature notification wrong gmsh version

---

.github/workflows/tests.yml
Makefile.am
config/t8_include.m4
config/t8_netcdf.m4
example/README
example/netcdf/Makefile.am
example/netcdf/t8_netcdf_status.c
test/Makefile.am
test/t8_test_netcdf_linkage.c

t8code can now be configured to link against netcdf.
Usage: configure --with-netcdf
Added example/netcdf/t8_netcdf_compilation_status.
This programs prints a message telling us whether t8code was linked against
netcdf or not.
Added test/t8_test_netcdf_linkage. If t8code was linked against netcdf this test
checks whether we are able to compile and execute netcdf code.
﻿- Add possibility to link against netcdf
- netcdf m4 file for configuring with netcdf
- Added a netcdf example that prints the compilation status.
- Add a test for netcdf linkage
- Add a with-netcdf variant to the github test workflow

Enable netcdf linkage

---

src/t8_cmesh/t8_cmesh.c

We have a bug in cmesh_new_hypercube when using it partitioned. See #79.
This commit introduces a warning message so that a user knows they should proceed with care.
See also #80

Feature warning message in cmesh hypercube

---

example/advect/t8_advection.cxx
example/tetgen/t8_forest_from_tetgen.cxx
example/tutorials/t8_step2_uniform_forest.cxx
example/tutorials/t8_step3_adapt_forest.cxx
example/tutorials/t8_step5_element_data.cxx
src/t8_forest.h
src/t8_forest/t8_forest.c
src/t8_forest/t8_forest_cxx.cxx
src/t8_forest/t8_forest_ghost.cxx
src/t8_forest/t8_forest_partition.cxx
src/t8_forest/t8_forest_vtk.cxx
test/t8_test_element_general_function.cxx
test/t8_test_ghost_exchange.cxx
test/t8_test_point_inside.cxx
test/t8_test_search.cxx
test/t8_test_transform.cxx

The name of the function to query the local number
of elements was misleading.
We changed it to be consistent with the name of
the function getting the global number of elements.

t8_forest_num_element -> t8_forest_get_local_num_elements

---

src/t8_forest/t8_forest_cxx.cxx

We wrongly used element_shape to distinguish
the interpolation patterns.
However, these depend on the tree class and
not the element.
We changed it back to tree_class

Fix forest_element_coordinate.

---

config/t8_vtk.m4
test/t8_test_vtk_linkage.cxx

- Fix spaces between '-l' libs.
- Disable T8_VTK_VERSION_USED if T8_WITH_VTK is not defined

Improve vtk configuration

---

src/t8_forest/t8_forest.c
src/t8_forest/t8_forest_balance.cxx
src/t8_forest/t8_forest_types.h

- Correct number of stats and stats collection
- Fix stats computation bug in balance
When more balance rounds are required than stats allocated,
the stats array grows dynamically.
However, we did not take into account that we do less partition
and ghost runs than adapt. (Since the last adapt does nothing,
so no ghost/partition needed).
This resulted in use of uninitialized values when more balances
rounds where needed.
We fixed this behaviour.
- Different stat counters for adapt,ghost,partition
- Introduced stat chunk size for dynamic growth
- Increase chunk size from 5 to 10

fix forest statistics bug

---

src/t8_forest/t8_forest_adapt.cxx

The recursion should only be entered for the last child of
a family.
This meant that it was also enteres for elements that only
have one child (i.e. vertices in the default scheme).
However, for this child the adapt callback was already called,
so recursively calling it is not necessary.

Fix a bug where recursive adaptation was falsely entered.

---

src/t8_forest/t8_forest_adapt.cxx

A logic error in an if-else construct made it possible
for a non-family to be detected as a family.
This resulted in elements being corsened that should
not have been allowed to coarsened.

Fix is_family check in adapt.

---

example/cmesh/t8_cmesh_partition.cxx
src/t8_cmesh/t8_cmesh_commit.c
src/t8_cmesh/t8_cmesh_offset.c
src/t8_cmesh/t8_cmesh_offset.h
src/t8_cmesh/t8_cmesh_partition.c
src/t8_cmesh/t8_cmesh_partition.h
src/t8_cmesh/t8_cmesh_save.c
src/t8_data/t8_shmem.c
src/t8_data/t8_shmem.h
src/t8_forest/t8_forest_cxx.cxx
src/t8_forest/t8_forest_partition.cxx
src/t8_geometry/t8_geometry.cxx
test/Makefile.am
test/t8_test_shmem.cxx

MPI shared memory needs to be initialized by setting inter and intranode communicators before using.
Added new t8_shmem_init and t8_shmem_finalize functions to t8_shmem.h and used them whenever shared memory is needed (cmesh_partition).
Adding warnings when used without initializing.

Feature init shared mem

---

doc/author_elsweijer.txt
src/t8_cmesh/t8_cmesh_readmshfile.c

Fixed numeration of gmsh msh hex node index to t8code hex node index

fixed numeration for msh hex nodes

---

src/t8_cmesh/t8_cmesh_readmshfile.c

For a face-to-face connection one face is declared
as the 'smaller face'. This info is used when the
orientation is computed.
For cmesh read msh file the computation of the smaller face
was wrong.
If both eclasses of the trees are the same then the 'smaller face'
is the face with smaller face_id.
Instead in readmshfile the face of the tree with smaller tree id
was used.
We fixed this behaviour.

Fix cmesh readmshfile bug with orientation

---

.github/workflows/mattermost.yml

Print a different message, when a PR is merged.

Different message for a merged pull_request

---

Makefile.am

grep -c WORD TXT only counts the lines where WORD occurs in TXT
With grep -o each occurance of WORD in TEXT is put out into a single line. We then count the number of lines.

Update gtest output

---

doc/mainpage.dox

I added a main page for the doxygen docu.
To view it compile doxygen with `make doxygen` and open the file `doxygen/html/index.html` in a browser. or navigate to `doxygen/latex`, type `make` and open the resulting `refman.pdf`.

Add a doxygen mainpage

---

test/t8_gtest_nca.cxx

Enhanced nca_check_deep-test
iterate over two different levels (`check_lvl_a` and `check_lvl_b`) and according to them the first and last descendants are computed. 
This enhancement includes the old functionality, as both variables run up to `elem_max_level`
closes #226 

Added nca-tests with different levels

---

src/t8_eclass.c
src/t8_eclass.h
test/t8_gtest_eclass.cxx

T8_ECLASS_INVALID was added to the enumerator t8_eclass to be used for the case t8code does not support a type of element that is used by a third-party library, for example vtk. As all other eclasses already have a meaning, this new class is introduced.

Added T8_ECLASS_INVALID

---

scripts/t8indent

The path of the file with additional data types that is used by t8indent was a relative path in the t8indent script.
This made the other scripts in /scripts that use indent not work, since they are required to be called from within /scripts, but then t8indent did not find the path.
We fixed this by using the absolute path, querying git for the repos path.

Fix indent script paths

---

Makefile.am

Install configuration files into `<sysconfdir>/t8code` instead of `<sysconfdir>`. See #152.

Move installed t8code configuration files into subdirectory

---

src/t8_forest.h

Removed a no longer implemented argument from the docstring.

Fix t8 forest set adapt docstring

---

AUTHORS
example/timings/time_forest_partition.cxx

The forest was copied two times in `time_forest_partition.cxx`

removed unnecessary forest movement

---

src/t8_forest.h
src/t8_forest/t8_forest.c

Reworked the vtk functions to achieve this behavior:
| linked to vtk  | 1           | 1                           | 1           | 1                | 1                         | 1                     | 1               | 1                         |
|----------------|-------------|-----------------------------|-------------|------------------|---------------------------|-----------------------|-----------------|---------------------------|
| write_ghosts   | 0           | 1                           | 0           | 0                | 1                         | 0                     | 1               | 1                         |
| write_curved   | 0           | 0                           | 1           | 0                | 1                         | 1 …

reworked vtk user functions

---

.github/workflows/tests.yml

Change the references in the github CI test action from "master" to "main"

Change master to main in github test action

---

src/Makefile.am

`src/t8_geometry/t8_geometry_implementations/t8_geometry_zero.hxx ` was listed twice in the Makefile, which lead to an error in my `make install`. I do not know why this doe not result in any problems on @Davknapp's system.

Fix-removed second occurrence of geometry zero in makefile

---

src/t8_cmesh/t8_cmesh_stash.h
src/t8_schemes/t8_default/t8_default_line/t8_dline_bits.h
src/t8_schemes/t8_default/t8_default_prism/t8_dprism_bits.h
src/t8_schemes/t8_default/t8_default_tet/t8_dtet_bits.h
src/t8_schemes/t8_default/t8_default_tri/t8_dtri_bits.h
src/t8_schemes/t8_default/t8_default_vertex/t8_dvertex_bits.h

Fixes compiler warnings that occur with gcc version 11.2.0.
This is the code part from previous PR #257 that we closed without merging.

Fix compiler warnings with newer gcc versions

---

.gitignore

As the name suggest, we add all files ending in '~' to the gitignore file.
These are backup files that are regularly created by text editors.

Add ~ Files to gitignore

---

src/t8_forest/t8_forest_vtk.cxx

closes #310 
We want to write the global-id just as if t8code wasn't linked with vtk.

Write the global tree id when linked with vtk

---

src/t8_schemes/t8_default/t8_default_tri/t8_dtri_bits.c

Fix a bug, where the linear id was computed wrong when the level was lower than t->level
level was always set to t->level, even if we want to compute the id on a lower level than t->level. 
Furthermore, the first computation of type_temp was wrong, too, because the level was not set correct. 
This PR fixes this issue.

fix in linear id for level < t->level

---

src/t8_geometry/t8_geometry_implementations/t8_geometry_linear.cxx
src/t8_geometry/t8_geometry_implementations/t8_geometry_linear.h

We implement a check function that queries whether a given geometry is of type t8_geometry_linear.
This function is required in some forest geometry implementations that assume that a given geometry is linear.

Check whether a given geometry is linear.

---

src/t8_forest/t8_forest_partition.cxx

Mini bugfix. When partition was executed with a single process a debugging message was printing 
an uninitialized value. This came up when running the code with valgrind.

Fix an uninitialized memory error in debug printing in partition

---

src/t8_element_c_interface.cxx
src/t8_element_cxx.hxx
src/t8_schemes/t8_default/t8_default_common/t8_default_common_cxx.cxx
src/t8_schemes/t8_default/t8_default_common/t8_default_common_cxx.hxx
src/t8_schemes/t8_default/t8_default_pyramid/t8_default_pyramid_cxx.cxx
src/t8_schemes/t8_default/t8_default_pyramid/t8_default_pyramid_cxx.hxx

The num_corners element function should not modify the eclass_scheme and should therefore be declared as const.
Many other element classes are also not const but should be - they are not covered in this PR.

Make num_corners function const.

---

test/t8_schemes/t8_gtest_init_linear_id.cxx

Similar to the first test I updated the scope of variables in the test and made the const if possible.

More const parameter in second linear_id-test

---

example/IO/cmesh/gmsh/t8_load_and_refine_square_w_hole.cxx
example/IO/cmesh/gmsh/t8_read_msh_file.cxx

Some of the older examples did not run correctly. Fixed that.
Added help message output for `example/IO/cmesh/gmsh/t8_read_msh_file.cxx` and fixed some compatibility issues in `example/IO/cmesh/gmsh/t8_load_and_refine_square_w_hole.cxx`.

Fix some examples

---

src/t8_element_c_interface.cxx
src/t8_element_c_interface.h
src/t8_element_cxx.hxx
src/t8_schemes/t8_default/t8_default_hex/t8_default_hex_cxx.cxx
src/t8_schemes/t8_default/t8_default_hex/t8_default_hex_cxx.hxx
src/t8_schemes/t8_default/t8_default_line/t8_default_line_cxx.cxx
src/t8_schemes/t8_default/t8_default_line/t8_default_line_cxx.hxx
src/t8_schemes/t8_default/t8_default_line/t8_dline_bits.c
src/t8_schemes/t8_default/t8_default_line/t8_dline_bits.h
src/t8_schemes/t8_default/t8_default_prism/t8_default_prism_cxx.cxx
src/t8_schemes/t8_default/t8_default_prism/t8_default_prism_cxx.hxx
src/t8_schemes/t8_default/t8_default_prism/t8_dprism_bits.c
src/t8_schemes/t8_default/t8_default_pyramid/t8_default_pyramid_cxx.cxx
src/t8_schemes/t8_default/t8_default_pyramid/t8_default_pyramid_cxx.hxx
src/t8_schemes/t8_default/t8_default_pyramid/t8_dpyramid_bits.c
src/t8_schemes/t8_default/t8_default_pyramid/t8_dpyramid_bits.h
src/t8_schemes/t8_default/t8_default_quad/t8_default_quad_cxx.cxx
src/t8_schemes/t8_default/t8_default_quad/t8_default_quad_cxx.hxx
src/t8_schemes/t8_default/t8_default_tet/t8_default_tet_cxx.cxx
src/t8_schemes/t8_default/t8_default_tet/t8_default_tet_cxx.hxx
src/t8_schemes/t8_default/t8_default_tri/t8_default_tri_cxx.cxx
src/t8_schemes/t8_default/t8_default_tri/t8_default_tri_cxx.hxx
src/t8_schemes/t8_default/t8_default_tri/t8_dtri_bits.c
src/t8_schemes/t8_default/t8_default_tri/t8_dtri_bits.h
src/t8_schemes/t8_default/t8_default_vertex/t8_default_vertex_cxx.cxx
src/t8_schemes/t8_default/t8_default_vertex/t8_default_vertex_cxx.hxx
src/t8_schemes/t8_default/t8_default_vertex/t8_dvertex_bits.c

The parameter identifying the vertex should be a const, since it should not change during the computation. This changes it. 

Made the parameter vertex a const-parameter for all elements.

---

src/t8_cmesh.h
src/t8_cmesh/t8_cmesh.c

This adds a function to print the vertices of each local tree of each cmesh.
If the cmesh is not partitioned, only process 0 prints the vertices of the cmesh. 
Otherwise the processes send their rank in a round-robin style, and after a process has received its message it prints the local trees and sends the next message. 
Why is this function necessary? I have a bug that mixes up the vertices and hope to find the source of the problem with this function. 
If the Pull request introduces code that is not covered by the github action (for example coupling …

Add a debug function that prints the trees of the cmesh

---

src/t8_schemes/t8_default/t8_default_pyramid/t8_default_pyramid_cxx.cxx
src/t8_schemes/t8_default/t8_default_pyramid/t8_dpyramid_bits.c
src/t8_schemes/t8_default/t8_default_pyramid/t8_dpyramid_bits.h

This PR introduces a new field 'switch_shape_at_level' for pyramid elements.
Everytime a pyramid is constructed we set this variable. If the shape of the constructed element is a pyramid, it is set to -1. Otherwise (the shape is a tetrahedron) we set it to the level of last ancestor in the shape of a tetrahedron.
This variable is then used in every other algorithm that needs information about ancestors and speeds up the computation significantly. First tests showed a speed-up around 20% for adapt and balance algorithms, without any changes in the other high-level algorithms.
As a reviewer please read through all the code lines and make sure that the code is fully …

Pyramid: compute and use switch_shape_at_level

---

.github/workflows/add_release_documentation.yml
.github/workflows/check_indentation.yml
.github/workflows/ci_playground.yml
.github/workflows/mattermost.yml
.github/workflows/tests.yml
.github/workflows/update_documentation.yml

Why? Before it was ubuntu-latest.
On December 1 github switched from Ubuntu 20.04 to 22.04.
This broke our tests, since the test script does not compile under the
new ubuntu (note that this does not mean that t8code does not run on
22.04).
Until the issue is resolved we revert manually back to 20.04.

Revert all ubuntu versions of github action to 20.04

---

test/Makefile.am

It seems like this line was not deleted during the conversion to a gtest

remove non-existent makefile source

---

doc/author_goldberg.txt
example/mptrac/t8_mptrac_interpolate.cxx

There was a bug within the interpolation of the y-coordinate (latitude) when using MPTRAC. The interpolation boundaries were swapped as it was assumed before the discretization was the other way round.

Fixed bug y reflection

---

src/t8_cmesh.h
src/t8_cmesh/t8_cmesh_types.h
src/t8_forest.h
src/t8_forest/t8_forest_ghost.h
src/t8_forest/t8_forest_types.h

Since questions about the variable `t8_gloidx_t  first_local_tree` came up at least twice in Mattermost, I extended the documentation a bit.
Changes to the code itself did not take place.

Tree indexing documentation

---

src/t8_element_cxx.hxx
src/t8_schemes/t8_default/t8_default_hex/t8_default_hex_cxx.hxx
src/t8_schemes/t8_default/t8_default_line/t8_default_line_cxx.hxx
src/t8_schemes/t8_default/t8_default_line/t8_dline_bits.c
src/t8_schemes/t8_default/t8_default_prism/t8_default_prism_cxx.hxx
src/t8_schemes/t8_default/t8_default_prism/t8_dprism_bits.c
src/t8_schemes/t8_default/t8_default_pyramid/t8_default_pyramid_cxx.hxx
src/t8_schemes/t8_default/t8_default_pyramid/t8_dpyramid_bits.c
src/t8_schemes/t8_default/t8_default_quad/t8_default_quad_cxx.hxx
src/t8_schemes/t8_default/t8_default_tet/t8_default_tet_cxx.hxx
src/t8_schemes/t8_default/t8_default_tet/t8_dtet_bits.c
src/t8_schemes/t8_default/t8_default_tri/t8_default_tri_cxx.hxx
src/t8_schemes/t8_default/t8_default_tri/t8_dtri_bits.c
src/t8_schemes/t8_default/t8_default_vertex/t8_default_vertex_cxx.hxx
src/t8_schemes/t8_default/t8_default_vertex/t8_dvertex_bits.c

Fixed issue #412 
Every ```t8_element_is_family (fam)``` check returns 0 if the input has a level 0 element.

Fix issue 412

---

src/t8_cmesh/t8_cmesh_readmshfile.cxx
src/t8_geometry/t8_geometry_implementations/t8_geometry_occ.cxx
src/t8_geometry/t8_geometry_implementations/t8_geometry_occ.h

Fixes #352
The ./t8_load_and_refine_square_w_hole example did not work in parallel since the geometries were not registered in parallel in the cmesh msh file reader.
Fixed it by registering the geometries on every rank.

Fix issue 352

---

src/t8_cmesh/t8_cmesh_readmshfile.cxx
src/t8_geometry/t8_geometry_implementations/t8_geometry_occ.cxx
src/t8_geometry/t8_geometry_implementations/t8_geometry_occ.h

Reverts DLR-AMR/t8code#380
The PR introduced a critical bug that a cmesh cannot be partitioned after reading with msh file version 4.

Revert "Fix issue 352"

---

configure.ac
tutorials/features/t8_features_curved_meshes.cxx

The arguments of the NACA tutorial were quite confusing. I fixed that. The [wiki article](https://github.com/DLR-AMR/t8code/wiki/Feature---Curved-meshes) will also be updated in s short time.

Reworked arguments of naca tutorial

---

src/t8_cmesh/t8_cmesh_commit.c

Remove outdated comment.
The ghost_facejoin_mempool is not actually given to sc_hash_new, it is used for other purposes. sc_hash_new gets a NULL pointer, so it allocates its own mempool

remove outdated TODO comment

---

doc/author_fussbroich.txt
example/geometry/t8_example_geometries.cxx

It would be useful to have a curved mesh output in the circle geometry example, because of the disorted elements on the border of the circle.

Enhancement curved output for geometry example

---

doc/author_schlottke-lakemper.txt
src/t8_schemes/t8_default/t8_default_prism/t8_default_prism_cxx.cxx
src/t8_schemes/t8_default/t8_default_prism/t8_dprism_bits.c
src/t8_schemes/t8_default/t8_default_tet/t8_default_tet.c

In some locations (to be exact: 4), the non-standard type `u_int64_t` was used, which prevents compiling t8code on some platforms (e.g., Linux with musl instead of glibc). This PR fixes this by using the standardized type `uint64_t`.
cc @jmark

Replace non-standard u_int64_t by t8_linearidx_t

---

src/t8_schemes/t8_default/t8_default_prism/t8_default_prism_cxx.cxx
src/t8_schemes/t8_default/t8_default_prism/t8_dprism_bits.c
src/t8_schemes/t8_default/t8_default_prism/t8_dprism_bits.h
src/t8_schemes/t8_default/t8_default_pyramid/t8_default_pyramid_cxx.cxx
src/t8_schemes/t8_default/t8_default_tet/t8_default_tet.c

Thanks to #473 I found several other cases where a ```uint64_t``` was used instead of ```t8_linearidx_t```. 
This PR fixes it.

Replace all uint64_t by t8_linearidx_t for the default-schemes

---

test/t8_gtest_vtk_linkage.cxx

There were two typos in the t8_gtest_vtk_linkage-test_suite, that only lead to a failure when t8code is linked with vtk. This PR fixes them. While doing CodeReview assure that t8code is linked with vtk. 

Fix vtk-linkage test

---

test/t8_schemes/t8_gtest_pyra_face_neigh.cxx

The pyra-test has not been properly indented  and the google-test-framework was not used as intended -  this PR fixes it. 

Updated pyra-tests

---

src/t8_schemes/t8_default/t8_default_hex/t8_default_hex_cxx.cxx
src/t8_schemes/t8_default/t8_default_hex/t8_default_hex_cxx.hxx
src/t8_schemes/t8_default/t8_default_line/t8_default_line_cxx.cxx
src/t8_schemes/t8_default/t8_default_line/t8_default_line_cxx.hxx
src/t8_schemes/t8_default/t8_default_line/t8_dline_bits.h
src/t8_schemes/t8_default/t8_default_prism/t8_default_prism_cxx.hxx
src/t8_schemes/t8_default/t8_default_prism/t8_dprism_bits.c
src/t8_schemes/t8_default/t8_default_prism/t8_dprism_bits.h
src/t8_schemes/t8_default/t8_default_pyramid/t8_default_pyramid_cxx.hxx
src/t8_schemes/t8_default/t8_default_pyramid/t8_dpyramid_bits.h
src/t8_schemes/t8_default/t8_default_quad/t8_default_quad_cxx.cxx
src/t8_schemes/t8_default/t8_default_quad/t8_default_quad_cxx.hxx
src/t8_schemes/t8_default/t8_default_tet/t8_default_tet_cxx.cxx
src/t8_schemes/t8_default/t8_default_tet/t8_default_tet_cxx.hxx
src/t8_schemes/t8_default/t8_default_tet/t8_dtet_bits.h
src/t8_schemes/t8_default/t8_default_tet/t8_dtri_to_dtet.h
src/t8_schemes/t8_default/t8_default_tri/t8_default_tri_cxx.cxx
src/t8_schemes/t8_default/t8_default_tri/t8_default_tri_cxx.hxx
src/t8_schemes/t8_default/t8_default_tri/t8_dtri_bits.c
src/t8_schemes/t8_default/t8_default_tri/t8_dtri_bits.h
src/t8_schemes/t8_default/t8_default_vertex/t8_default_vertex_cxx.cxx
src/t8_schemes/t8_default/t8_default_vertex/t8_default_vertex_cxx.hxx
src/t8_schemes/t8_default/t8_default_vertex/t8_dvertex_bits.h

Doing some refactoring for the following PUMA patches PR

Feature puma patches [1/x] refactoring

---

src/t8_element_cxx.hxx
src/t8_schemes/t8_default/t8_default_common/t8_default_common_cxx.hxx
src/t8_schemes/t8_default/t8_default_hex/t8_default_hex_cxx.cxx
src/t8_schemes/t8_default/t8_default_hex/t8_default_hex_cxx.hxx
src/t8_schemes/t8_default/t8_default_line/t8_default_line_cxx.cxx
src/t8_schemes/t8_default/t8_default_line/t8_default_line_cxx.hxx
src/t8_schemes/t8_default/t8_default_prism/t8_default_prism_cxx.cxx
src/t8_schemes/t8_default/t8_default_prism/t8_default_prism_cxx.hxx
src/t8_schemes/t8_default/t8_default_pyramid/t8_default_pyramid_cxx.cxx
src/t8_schemes/t8_default/t8_default_pyramid/t8_default_pyramid_cxx.hxx
src/t8_schemes/t8_default/t8_default_quad/t8_default_quad_cxx.cxx
src/t8_schemes/t8_default/t8_default_quad/t8_default_quad_cxx.hxx
src/t8_schemes/t8_default/t8_default_tet/t8_default_tet_cxx.cxx
src/t8_schemes/t8_default/t8_default_tet/t8_default_tet_cxx.hxx
src/t8_schemes/t8_default/t8_default_tri/t8_default_tri_cxx.cxx
src/t8_schemes/t8_default/t8_default_tri/t8_default_tri_cxx.hxx
src/t8_schemes/t8_default/t8_default_vertex/t8_default_vertex_cxx.cxx
src/t8_schemes/t8_default/t8_default_vertex/t8_default_vertex_cxx.hxx

The interface for the coming element ref coord functions. The function gets a set of reference coordinates inside an element $[0, 1]^d$ and maps these coordinates to the reference coordinates of the tree $[0, 1]^d$, regarding the anchor coordinate, level and orientation. This way, we can evaluate the geometry of arbitrary points inside an element. Before, we could only evaluate the vertices of the elements.
If the Pull request introduces code that is not covered by the github action (for example coupling with a new …

Feature puma patches [2/x] add element ref coords interface

---

doc/Doxyfile.in

Fixes the documentation, which was broken in #499 

Enable recursive documentation and remove file patterns

---

README.md

- Unifty first/last name order in references
- Add line breaks

quality improvements in README

---

doc/Doxyfile.in

Adds our link flags to the preprocessor macros of Doxygen. This way, Doxygen also generates the documentation behind a `T8_ENABLE_DEBUG`, `T8_WITH_VTK`, ... macro.
Fixes #426 

Add preprocessor macros for documentation

---

src/t8_schemes/t8_default/t8_default_tri/t8_dtri_bits.c

Closes #545 
Removed a ```T8_ASSERT(t8_dtri_is_valid(elem)```.
This assertion was called with a pyramid as an argument, too, because the function gets called when t8_dpyramid_compute_reference_coords is called with a tetrahedral descendant. The Assertion fails, because elem->eclass_int8 is not set correctly (line 1727 in t8_dtri_bits.c)
In a pure tetrahedral or triangular scheme the check is called in t8_default_tet/tri_cxx.cxx

Remove a t8_dtri_is_valid assertion, that gets called with a pyramid-descendant

---

src/t8_cmesh/t8_cmesh_examples.c

Added a newline in cmesh examples warnings output.

---

src/t8_schemes/t8_default/t8_default_pyramid/t8_dpyramid_bits.c

The implementation of pyramid element reference coordinates was faulty:
This can only be observed, if the pyramids are written out as curved and if the nonlinear subdivision level in ParaView is >0.
After the fix, it looks like this:
Here is a quick code for generating pyramids and write them as curved elements:
```
#include <t8.h>
#include <t8_cmesh/t8_cmesh_examples.h>
#include <t8_forest/t8_forest_general.h>
#include <t8_forest/t8_forest_geometrical.h>
#include <t8_forest/t8_forest_profiling.h>
#include <t8_forest/t8_forest_io.h>
#include <t8_forest/t8_forest_vtk.h>
#include <t8_schemes/t8_default/t8_default_cxx.hxx>
int main(int argc, char **argv)
{ 
int mpiret = sc_MPI_Init (&argc, &argv);
SC_CHECK_MPI (mpiret);
sc_init (sc_MPI_COMM_WORLD, 1, 1, …
```

Fix pyramid element ref coords

---

doc/author_andreev.txt
src/t8_forest/t8_forest.c
src/t8_forest/t8_forest_io.h

Added constness to flags

---

src/t8_forest/t8_forest_general.h

**Added constancy to flags in t8_forest_replace_t**

Added constancy to flags in t8_forest_replace_t

---

doc/author_geihe.txt
tutorials/general/t8_step4_partition_balance_ghost.cxx

Switched to `t8_forest_write_vtk_ext` to be able to pass flag for writing ghost cells.

Enable ghost cell output in tutorial step 4

---

src/t8_cmesh/t8_cmesh_testcases.c

reduced num testscases for LESS-TESTS

---

test/t8_data/t8_gtest_shmem.cxx

Replace loops over parameters by googletest-functionality.
Closes #554 

Parametrize shmem test

---

example/advect/t8_advection.cxx
src/t8_forest/t8_forest_cxx.cxx
src/t8_vtk/t8_vtk_reader.cxx

Tere were a few small personal print outputs that were probably overlooked in past reviews. Mostly for debugging.

removed individual t8_debugf

---

src/t8_vtk/t8_vtk_types.h
test/t8_IO/t8_gtest_vtk_reader.cxx

Parametrized the existing test and added a test for pointSets. 

Parametrize vtk tests

---

src/t8_vtk/t8_vtk_reader.cxx
test/t8_IO/t8_gtest_vtk_reader.cxx

First I enhanced the tests by checking also the partitioned read (only one proc reads) and checking different main_procs. 
An error occured that I fixed, too. 

Vtk parallel checks

---

src/t8_cmesh/t8_cmesh_netcdf.c
src/t8_cmesh/t8_cmesh_vtk_writer.c
src/t8_eclass.c
src/t8_eclass.h
src/t8_element_shape.c
src/t8_forest/t8_forest_vtk.cxx
test/t8_gtest_eclass.cxx

Closes #104 
Adds new look-up table, updates the look-up tables used in the function and adds a test for the look-up table. 

Fix eclass vtk corner number

---

src/t8_forest/t8_forest_cxx.cxx

Adapt MPI_INT to sc_MPI_INT to enable serial build

Fix serial build

---

src/t8_schemes/t8_default/t8_default_hex/t8_default_hex_cxx.cxx
src/t8_schemes/t8_default/t8_default_quad/t8_default_quad_cxx.cxx

Currently, due to an assertion, the t8_element_child function cannot be called with the same element for input and output for quads and hexs in debug mode. According to the documentation, it should be.
This PR introduces the change that the assertion to check that the input is the parent of the output is only called, when input and output element differ.

Fix t8_element_child for quads and hexs when input=output

---

.github/workflows/add_release_documentation.yml
.github/workflows/update_documentation.yml

Our new doxyfiles require doxygen > 1.9 but the standard version for ubuntu 20.04 is 1.8.x. Therefore we upgrade to Ubuntu 22.04

update github runners to 22.04 due to new doxygen version requirements

---

test/t8_gtest_eclass.cxx

Closes #600 
Parametrize the eclass test. Seperate the valid-class check into two seperate functions. 

Parametrize gtest eclass

---

src/t8_data/t8_shmem.c
src/t8_data/t8_shmem.h
test/t8_data/t8_gtest_shmem.cxx

Wrapper for sc_shmem_prefix + a simple test. 

Implemented wrapper for sc_shmem_prefix

---

.github/dependabot.yml

This workflow checks your other workflows and creates a PR to update your GH actions if a new version for any action you use has been released. We nowadays use this in virtually every repository in the Trixi Framework.
My motivation is that I noticed in several of your workflow files some outdated versions of actions are used, e.g., the `checkout` action at v1 (instead of the current v3), e.g., here:
https://github.com/DLR-AMR/t8code/blob/fa2f075a788ab2580b046e2170993a73c10307b8/.github/workflows/tests_sc_p4est.yml#L59
An example PR that is created by Dependabot can be seen, e.g., here:
https://github.com/trixi-framework/libtrixi/pull/40
As a reviewer please read through all the code lines and make …

Automatically update GitHub Actions via Dependabot

---

.github/workflows/check_indentation.yml
.github/workflows/mattermost.yml
.github/workflows/tests_sc_p4est.yml
.github/workflows/tests_t8code_linkage_parallel_debug.yml
.github/workflows/tests_t8code_linkage_parallel_release.yml
.github/workflows/tests_t8code_parallel.yml
.github/workflows/tests_t8code_serial.yml

Right now, all scheduled workflows run unconditionally in all forks. While this is likely neither required nor intended, it is also annoying because most workflows seem to fail when executed on a fork, e.g., [this one](https://github.com/sloede/t8code/actions/runs/5594638751/jobs/10229692683), and thus cause a number of failure notifications from GitHub each night.
This PR adds a guard to all workflows with a `schedule` trigger that ensures that `schedule` only triggers a workflow on the main repository.
For good measure, I also disabled the Mattermost workflow on forks, since it also does not seem to be applicable, always fails, and is triggered by things like syncing your fork with the upstream repo.
**_All these boxes must be checked by the reviewers …

Disable non-applicable workflows on forks

---

.github/workflows/mattermost.yml

After merging a PR, Code is pushed into main, therefore triggering the wf twice. This PR fixes it. 
Closes #212 

Only trigger the workflow on PR-events.

---

.github/workflows/update_documentation.yml

The workflow update_documentation failed if no changes where to commit. 
This PR should fix it by looking at git diff befor commiting. 
Test-run: https://github.com/DLR-AMR/t8code/actions/runs/5645602999/job/15291708751

Add check to only commit and push if there are changes

---

src/t8_forest/t8_forest.c

For some reason a superfluous ifdef pragma slipped in which disables the uncurved VTK output when not linking against VTK library and set `write_curved = 1`. In my opinion we do not need this check which is already covered some lines below.

Renable VTK output without linking to VTK library

---

example/cmesh/t8_cmesh_set_join_by_vertices.cxx
src/t8_cmesh/t8_cmesh_helpers.h
src/t8_schemes/t8_default/t8_default_pyramid/t8_dpyramid.h
src/t8_schemes/t8_default/t8_default_pyramid/t8_dpyramid_bits.c
test/t8_schemes/t8_gtest_pyra_connectivity.cxx

Fix minor typo in pyramid scheme.

---

src/t8_forest/t8_forest_vtk.cxx

Simplified data-writing and used the proper functions to set scalars. 

Pretify Data-writing

---

doc/author_kirby.txt
src/t8_forest/t8_forest_cxx.cxx

Fix memory leak in t8_forest_leaf_face_neighbors: `face_element` was not destroyed.
Closes #672.
Added BSD license for contributions.

Fix t8 forest leaf face neighbors memleak

---

src/t8_forest/t8_forest.c
src/t8_forest/t8_forest_cxx.cxx
src/t8_forest/t8_forest_iterate.cxx
src/t8_forest/t8_forest_partition.cxx
src/t8_forest/t8_forest_private.h
src/t8_schemes/t8_default/t8_default_common/t8_default_common_cxx.cxx
test/t8_forest/t8_gtest_half_neighbors.cxx
test/t8_schemes/t8_gtest_ancestor.cxx
test/t8_schemes/t8_gtest_nca.cxx

Clean version of #676, closes #672 
Memory that is allocated by `t8_element_new`, but not destroyed by `t8_element_destroy`, stays in the memory pool until the scheme is destroyed. This leads to an increasing memory footprint that doesn't show up as an error with the `sc` library or with `valgrind`.
Therefore, an assertion is introduced in the destructor of the scheme, that all elements were explicitely given back to the memory pool.
Additionally, many occurences of missing `t8_element_destroy` statements were found and fixed.
As a reviewer please read through all the code lines and make sure that the code is fully understood, bug free, well-documented and …

Add t8_element_destroy statements to improve memory management

---

src/t8_vtk/t8_vtk_reader.cxx

Free the memory of the filter itself. 

Delete filter after usage

---

test/t8_forest_incomplete/t8_gtest_empty_global_tree.cxx
test/t8_forest_incomplete/t8_gtest_empty_local_tree.cxx
test/t8_forest_incomplete/t8_gtest_iterate_replace.cxx
test/t8_forest_incomplete/t8_gtest_permute_hole.cxx
test/t8_forest_incomplete/t8_gtest_recursive.cxx

indent test_t8_forest_incomplete files

---

test/t8_IO/t8_gtest_vtk_reader.cxx

Update indentation test-t8_IO

---

example/common/t8_example_common.cxx
example/common/t8_example_common.h

Change indentation of comments from two to one lines

Update indentation example-common

---

benchmarks/t8_time_prism_adapt.cxx
benchmarks/time_forest_partition.cxx

Updated some sc_option statements to our new column-length. 

Update prints to new column length.

---

test/t8_schemes/t8_gtest_ancestor.cxx
test/t8_schemes/t8_gtest_descendant.cxx
test/t8_schemes/t8_gtest_element_count_leafs.cxx
test/t8_schemes/t8_gtest_face_descendant.cxx
test/t8_schemes/t8_gtest_find_parent.cxx
test/t8_schemes/t8_gtest_init_linear_id.cxx
test/t8_schemes/t8_gtest_nca.cxx
test/t8_schemes/t8_gtest_pyra_face_neigh.cxx
test/t8_schemes/t8_gtest_successor.cxx

Remove indent on/off comments test schemes

---

scripts/README.md

Replaced GNU-Indent text-parts with clang-format
Deleted a section about GNU-Indent specific problems. 

From GNU-indent to clang-format

---

src/t8_vtk/t8_vtk_reader.cxx

Return NULL if we get NULL as an input vtkGrid. 
This can happen if we read a parallel file with  more procs than files. This way, the proc will stay "empty"

Improve vtkGrid_to_vtkPointSet

---

pull_request_template.md

This is not necessary anymore since we switched to clang-format.

remove custom datatypes from pr template

---

.github/workflows/update_documentation.yml

The set-output function of GitHub Actions as deprecated and that's why our documentation is not longer automatically updated. (https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
Fixed this by using environment variables instead.

Fix documentation CI

---

src/t8_forest/t8_forest_vtk.cxx

The SetScalars()/SetVectors() function lead to only activating the last dataarray. This fixes it by using AddArray() instead. 

Improve forest vtk writer api

---

src/t8_forest/t8_forest_cxx.cxx
src/t8_forest/t8_forest_general.h
test/t8_geometry/t8_gtest_point_inside.cxx

Implemented a batched version of the function t8_forest_element_point_inside. 
With the updated implementation we avoid computations that prepare the actuall inside-check for each point check. 
instead this preparing step is done once and then all points are checked. 

Feature batch processing t8 forest element point inside

---

src/t8_eclass.c

There is a bug in the eclass_compare function; this pull request fixes it.
Fix eclass_compare function for T8_ECLASS_PYRAMID type: should be +1 instead of -1.

Bug fix: eclass_compare

---

test/t8_gtest_eclass.cxx

Added a test to prevent other bugs like in #770 

Check the inequalities definied for eclasses

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md

I got the suggestions from the reviewers for the Helmholtz Incubator Software Award that some hints about
contributing to t8code and our code-of-conduct would be nice. So I just added some standard ones.

Added contribution notes and code of conduct.

---

src/t8_forest/t8_forest_cxx.cxx

The PR restores the former calculation of the element centroid in t8_forest_cxx.cxx.
This solves the problems regarding triangular meshes used in the advection example, as described in issue #773.

Fix issue #773

---

test/t8_gtest_eclass.cxx

To prevent bugs like in #778 
Creates a cmesh with a single tree of a class, and computes the normal of each face, based on the vertex order described in the look-up table. Computing the signed distance from the normal to the center (w.r.t to vertex 0) tells if the normal points inwards or outwards.

Added a test for the face-orientation

---

.github/workflows/mattermost.yml

Test adapted workflow

---

src/t8.c
src/t8.h
src/t8_forest/t8_forest.c
src/t8_forest/t8_forest_cxx.cxx
src/t8_forest/t8_forest_general.h
src/t8_forest/t8_forest_ghost.cxx
src/t8_forest/t8_forest_ghost.h

In many cases we want to get something from the forest, but the params of these getter functions weren't const. 
It anoyed me and on this branch I introduced const params for the most easy getter functions, where I did not have to introduce bigger changes. 

More const params

---

src/t8_forest/t8_forest_types.h

Add a comment on the usage of the incomplete trees flag of a forest.
This flag is collective, so has the same value on each process.
The usage comment now reflects that.
Please note that i was not able to indent the code properly since my clang version is currently too old.

Add a comment on the usage of the incomplete trees flag of a forest

---

src/t8_forest/t8_forest_ghost.cxx

Abort the execution if Ghost is executed on a forest with incomplete trees.
This is necessary since the Ghost computation may fail on meshes with holes. See #825.
This behaviour can be reverted when #825 is fixed. 

Add abort message to Ghost algorithm when using deleted elements

---

src/t8_element_c_interface.h
src/t8_element_cxx.hxx
src/t8_schemes/t8_default/t8_default_hex/t8_default_hex_cxx.cxx
src/t8_schemes/t8_default/t8_default_hex/t8_default_hex_cxx.hxx
src/t8_schemes/t8_default/t8_default_line/t8_default_line_cxx.hxx
src/t8_schemes/t8_default/t8_default_prism/t8_default_prism_cxx.hxx
src/t8_schemes/t8_default/t8_default_pyramid/t8_default_pyramid_cxx.hxx
src/t8_schemes/t8_default/t8_default_quad/t8_default_quad_cxx.cxx
src/t8_schemes/t8_default/t8_default_quad/t8_default_quad_cxx.hxx
src/t8_schemes/t8_default/t8_default_tet/t8_default_tet_cxx.cxx
src/t8_schemes/t8_default/t8_default_tet/t8_default_tet_cxx.hxx
src/t8_schemes/t8_default/t8_default_tri/t8_default_tri_cxx.cxx
src/t8_schemes/t8_default/t8_default_tri/t8_default_tri_cxx.hxx
src/t8_schemes/t8_default/t8_default_vertex/t8_default_vertex_cxx.hxx

Deleted the element-function `t8_element_boundary` - no element in the default scheme implemented it. 

Delete element boundaries

---

src/t8_cmesh/t8_cmesh_examples.c

Implemented a function for redundant computations and function calls in t8_cmesh_examples.c

Fixed TODO for code duplication in t8_cmesh_examples.c

---

example/advect/t8_advection.cxx
example/forest/t8_test_face_iterate.cxx
src/t8_forest/t8_forest.c
src/t8_forest/t8_forest_balance.cxx
src/t8_forest/t8_forest_cxx.cxx
src/t8_forest/t8_forest_general.h
src/t8_forest/t8_forest_iterate.cxx
src/t8_forest/t8_forest_netcdf.cxx
src/t8_forest/t8_forest_partition.cxx
test/t8_forest/t8_gtest_ghost_exchange.cxx
test/t8_forest/t8_gtest_half_neighbors.cxx
test/t8_forest_incomplete/t8_gtest_iterate_replace.cxx
test/t8_schemes/t8_gtest_element_ref_coords.cxx
tutorials/general/t8_step6_stencil.cxx

This PR fixes #28.
- `t8_forest_get_element` now returns a `const t8_element_t*`
- `t8_forest_get_element_in_tree` now returns a `const t8_element_t*`
We do these changes since both getter functions are part of the public interface and users should not be able to modify elements of the forest.
Before merging please double check that this integrates easily into user codes. Especially Trixi @jmark 

Feature issue28 get element return const

---

src/t8_cmesh/t8_cmesh_partition.c

It is the only function that exits to send/recvrange, therefore it is not necessary to call it the alternative.
Updated the name and improved some minor parts of the code.

Update cmesh partition alternative sendrecv range

---

test/t8_cmesh/t8_gtest_bcast.cxx
test/t8_cmesh/t8_gtest_cmesh_copy.cxx
test/t8_cmesh/t8_gtest_cmesh_face_is_boundary.cxx
test/t8_cmesh/t8_gtest_cmesh_partition.cxx
test/t8_cmesh/t8_gtest_cmesh_set_join_by_vertices.cxx
test/t8_cmesh/t8_gtest_hypercube.cxx
test/t8_forest/t8_gtest_element_general_function.cxx
test/t8_forest/t8_gtest_element_volume.cxx
test/t8_forest/t8_gtest_find_owner.cxx
test/t8_forest/t8_gtest_forest_commit.cxx
test/t8_forest/t8_gtest_ghost_and_owner.cxx
test/t8_forest/t8_gtest_ghost_exchange.cxx
test/t8_forest/t8_gtest_half_neighbors.cxx
test/t8_forest/t8_gtest_search.cxx
test/t8_forest_incomplete/t8_gtest_empty_global_tree.cxx
test/t8_forest_incomplete/t8_gtest_iterate_replace.cxx
test/t8_forest_incomplete/t8_gtest_permute_hole.cxx
test/t8_gtest_eclass.cxx
test/t8_gtest_macros.hxx
test/t8_schemes/t8_gtest_default.cxx
test/t8_schemes/t8_gtest_descendant.cxx
test/t8_schemes/t8_gtest_dfs_base.hxx
test/t8_schemes/t8_gtest_element_count_leafs.cxx
test/t8_schemes/t8_gtest_element_ref_coords.cxx
test/t8_schemes/t8_gtest_face_descendant.cxx
test/t8_schemes/t8_gtest_face_neigh.cxx
test/t8_schemes/t8_gtest_find_parent.cxx
test/t8_schemes/t8_gtest_init_linear_id.cxx
test/t8_schemes/t8_gtest_nca.cxx
test/t8_schemes/t8_gtest_scheme_helper.hxx

Helper class to test scheme functionality on all elements by DFS
Also enables this for `find_parent`, more to come

Helper class to test scheme functionality on all elements by DFS

---

src/t8_cmesh/t8_cmesh.c
src/t8_cmesh/t8_cmesh_examples.c
src/t8_cmesh/t8_cmesh_triangle.c
src/t8_geometry/t8_geometry_with_vertices.h

replace t8_locidx_t by t8_gloidx_t

---

example/forest/t8_face_neighbor.cxx
src/t8_element_c_interface.cxx
src/t8_element_c_interface.h
src/t8_element_cxx.hxx
src/t8_schemes/t8_default/t8_default_hex/t8_default_hex_cxx.cxx
src/t8_schemes/t8_default/t8_default_hex/t8_default_hex_cxx.hxx
src/t8_schemes/t8_default/t8_default_line/t8_default_line_cxx.cxx
src/t8_schemes/t8_default/t8_default_line/t8_default_line_cxx.hxx
src/t8_schemes/t8_default/t8_default_prism/t8_default_prism_cxx.cxx
src/t8_schemes/t8_default/t8_default_prism/t8_default_prism_cxx.hxx
src/t8_schemes/t8_default/t8_default_pyramid/t8_default_pyramid_cxx.cxx
src/t8_schemes/t8_default/t8_default_pyramid/t8_default_pyramid_cxx.hxx
src/t8_schemes/t8_default/t8_default_quad/t8_default_quad_cxx.cxx
src/t8_schemes/t8_default/t8_default_quad/t8_default_quad_cxx.hxx
src/t8_schemes/t8_default/t8_default_tet/t8_default_tet_cxx.cxx
src/t8_schemes/t8_default/t8_default_tet/t8_default_tet_cxx.hxx
src/t8_schemes/t8_default/t8_default_tri/t8_default_tri_cxx.cxx
src/t8_schemes/t8_default/t8_default_tri/t8_default_tri_cxx.hxx
src/t8_schemes/t8_default/t8_default_vertex/t8_default_vertex_cxx.cxx
src/t8_schemes/t8_default/t8_default_vertex/t8_default_vertex_cxx.hxx

Element root len was only used for debug-output. 
Deleted the debugging output and the function

Delete element root len

---

src/t8_cmesh/t8_cmesh.c

When destroying a cmesh in debugging mode we did not checkwhether the communicator was created before checking whether it is valid.
This resulted in a crash in certain scenarios, i.e. setting a partition offset, not committing the cmesh and destroying it.
Related to #869  #868 

in cmesh_reset only check comm valid if cmesh is committed

---

src/t8_forest/t8_forest_cxx.cxx
src/t8_forest/t8_forest_geometrical.h

Title says it all. Only some compiler versions make `inline [...]` routines in header files also visible as symbols in shared libraries which application then can use in their code. Otherwise the routine is statically inlined in the t8code library and cannot be called by external applications.

Moved t8_forest_element_from_ref_coords implementation into cxx file.

---

src/t8_cmesh/t8_cmesh_readmshfile.cxx
src/t8_geometry/t8_geometry_helpers.c
src/t8_geometry/t8_geometry_implementations/t8_geometry_occ.cxx

Fixes some bugs in the curved geometry:
1. Checks if two nodes are on the same geometry, if both nodes of an edge lie on geometries with different dimensions.
2. Adds a break so that the default of that switch is not reached
3. Uses the right lookup table for edges

Bugfixes in curved geometry

---

src/t8_cmesh/t8_cmesh_partition.c
src/t8_geometry/t8_geometry.cxx
src/t8_geometry/t8_geometry.h

Cause of the error: 
During partitioning of the cmesh vertex-data of the tree can be moved around. If the active tree of the geometry is the same as befor partitioning the vertex-data has been moved without notifying the geometry. 
Solution:
The active tree of the geometry-handler is set to a negative value that is out of bounds of the possible ltreeids. Therefore the active tree is set again as soon as we want to load tree data and the tree-data is actually loaded. 
Thanks to @lukasdreyer for helping with the bug-hunt.
Closes #873 
If the Pull request …

Fix Bug 873

---

.github/workflows/check_indentation.yml
src/t8_cmesh/t8_cmesh_examples.c
src/t8_vec.h
test/t8_schemes/t8_gtest_boundary_extrude.cxx
test/t8_schemes/t8_gtest_dfs_base.hxx
test/t8_schemes/t8_gtest_equal.cxx
tutorials/general/t8_step7_interpolation.cxx

The indentation check CI Pipeline was not working correctly.
Redirecting stderr to stdout after calling the indentation script check overwrites the exit code, therefore always showing that the indentation check worked.
This PR fixes that problem and the indentation errors that were introduced in the meantime.
See the follwing CI Job for an example of a failing run:
https://github.com/DLR-AMR/t8code/actions/runs/7407043980/job/20152521092
Please also delete branch `indent_fail_check` when merging.
If the Pull request …

Fix indentation CI and indentation

---

test/t8_schemes/t8_gtest_dfs_base.hxx
test/t8_schemes/t8_gtest_equal.cxx
test/t8_schemes/t8_gtest_face_descendant.cxx

Use new DFS test structure for existing test

Use dfs base for face descendant test

---

test/Makefile.am
test/t8_forest/t8_gtest_ghost_delete.cxx

Ghost currently does not work on forests with deleted elements. This test is an example of a configuration that fails.
See #825.
It does not fail when the second adapt call is done without ghosts

Test ghost for forests with holes

---

src/t8_geometry/t8_geometry_with_vertices.h

This PR fixes the root cause for https://github.com/DLR-AMR/T8code.jl/issues/47 in T8code.jl.

Added missing `t8_cmesh.h` include in `t8_geometry_with_vertices.h`

---

.github/workflows/tests_sc_p4est.yml
.github/workflows/tests_t8code_linkage_parallel_debug.yml
.github/workflows/tests_t8code_linkage_parallel_release.yml
.github/workflows/tests_t8code_parallel.yml
.github/workflows/tests_t8code_serial.yml
Makefile.am
config/ax_cxx_compile_stdcxx.m4
config/t8_include.m4
config/t8_stdpp.m4
configure.ac
test/Makefile.am

Enforce C++17
Uses https://www.gnu.org/software/autoconf-archive/ax_cxx_compile_stdcxx.html
Also limits the number of processes for the make check command in the github actions workflow to 8, because leaving it unlimited lead to weird racing conditions during compiling in the docker container. This could not be replicated when manually trying to repeat the build process in the docker container.

Enforce c++ 17

---

src/t8_cmesh.h
src/t8_cmesh/t8_cmesh.c
test/Makefile.am
test/t8_cmesh/t8_gtest_attribute_gloidx_array.cxx

A new setter and getter for cmesh attributes of type t8_gloidx_t array.
That is multiple t8_gloidx_t entries.
- Implement t8_cmesh_set_attribute_gloidx_array 
- Implement t8_cmesh_get_attribute_gloidx_array 
- Implement a test for set/get with a cmesh with 2 trees.
- Also made minor changes on the existing attribute functions that i believe to be small enough to inlcude here, even though
they could be their own PR.
If the Pull request introduces code that is not covered by the github action (for example coupling with a new …

Feature set attribute gloidx array

---

doc/author_schoenlein.txt
src/t8_schemes/t8_default/t8_default_tri/t8_dtri.h
src/t8_schemes/t8_default/t8_default_tri/t8_dtri_bits.c

The value n for triangles was never used anywhere. For that reason we deleted it.

remove no longer needed entry for default_triangles

---

test/t8_schemes/t8_gtest_equal.cxx
test/t8_schemes/t8_gtest_face_descendant.cxx

There are two tests, that run much longer than the other scheme dfs tests, because their workload to check an element is much higher. For these tests, the max check lvl was decreased.

decrese maxlvl to bring testruntime down

---

test/t8_forest/t8_gtest_forest_commit.cxx
test/t8_schemes/t8_gtest_face_descendant.cxx
test/t8_schemes/t8_gtest_face_neigh.cxx
test/t8_schemes/t8_gtest_successor.cxx

Changed enable debug with enable less tests

Reduce runtime of tests

---

test/t8_gtest_macros.hxx

include cmesh_testcases.h in gtest_macros
move includes inside include guards

add testcase include and change include order in gtest_macros

---

test/Makefile.am
test/t8_cmesh/t8_gtest_cmesh_copy.cxx

Added a test for cmesh_copy (i.e. derive without any additions).
The test fails currently on several test cases and is thus deactivated.
See also #920 

Feature test cmesh copy

---

.github/workflows/add_release_documentation.yml

Let T8ddy automatically rewrite the redirection to the latest documentation

Let t8ddy update latest dev redirection

---

src/t8_cmesh/t8_cmesh_vtk_writer.c
src/t8_forest/t8_forest_vtk.cxx
src/t8_vtk.h

The cmesh vtk had macros distinguishing between binary/compressed VTK output and ascii output.
Even though only the ascii version was implemented.
Since we do not plan on implementing the compressed output, and the setting was not even in the configure, we remove it completely.
This cleans up the code.

Remove binary vtk option

---

src/t8_cmesh.h
src/t8_cmesh/t8_cmesh.c

This PR fixes a typo in the documentation. 
Furhtermore the documentation was duplicated in the .c-file and therefore deleted. 

Fix typo, and delete documentation in .c-file (duplicate)

---

benchmarks/time_forest_partition.cxx
benchmarks/time_partition.cxx
example/IO/cmesh/gmsh/t8_load_and_refine_square_w_hole.cxx
example/IO/cmesh/gmsh/t8_read_msh_file.cxx
example/IO/cmesh/t8_cmesh_load_save.cxx
example/IO/cmesh/tetgen/t8_forest_from_tetgen.cxx
example/IO/cmesh/tetgen/t8_read_tetgen_file.cxx
example/IO/cmesh/tetgen/t8_time_tetgen_file.cxx
example/IO/cmesh/triangle/t8_read_triangle_file.cxx
example/IO/cmesh/vtk/t8_cmesh_read_from_vtk.cxx
example/advect/t8_advection.cxx
example/cmesh/t8_cmesh_geometry_examples.cxx
example/cmesh/t8_cmesh_hypercube_pad.cxx
example/cmesh/t8_cmesh_partition.cxx
example/forest/t8_test_face_iterate.cxx
example/forest/t8_test_ghost.cxx
example/forest/t8_test_ghost_large_level_diff.cxx
src/t8_cmesh/t8_cmesh_vtk_writer.c
src/t8_cmesh_vtk_writer.h
tutorials/general/t8_step1_coarsemesh.cxx
tutorials/general/t8_tutorial_build_cmesh.cxx

The cmesh vtk function had a scale parameter that was never implemented.
Since the desired feature is the same as Paraviews Shrink filter, we will also never implement it.
Removed the scale parameter from the interface.
Note that this will trigger a major release.

Remove scale parameter from cmesh vtk

---

example/cmesh/t8_cmesh_geometry_examples.cxx

The PR https://github.com/DLR-AMR/t8code/pull/927 was quite old and was not recently merged with `main` before approving the changes. Hence, some deletions of scale parameters were missed.

Removed missing scale parameter deletions.

---

test/t8_cmesh_generator/t8_cmesh_example_sets.hxx
test/t8_cmesh_generator/t8_cmesh_parametrized_examples/t8_cmesh_new_comm.hxx
test/t8_cmesh_generator/t8_gtest_cmesh_cartestian_product.hxx

To reduce the amount of code that needs to be added, I added a constructor for cmeshes that have the same signature. 

Add new constructor for similar cmeshes

---

test/t8_cmesh_generator/t8_cmesh_example_sets.hxx
test/t8_cmesh_generator/t8_cmesh_parametrized_examples/t8_cmesh_new_hypercube_param.hxx
test/t8_cmesh_generator/t8_cmesh_parametrized_examples/t8_cmesh_params.hxx

Add a new example to the parametrized tests.
Splitted the tests into two parts, because pyramids do not support a periodic hypercube (yet). 

Add new test

---

src/t8_cmesh/t8_cmesh_examples.c

Discovered a bug in the hypercube_pad example, where the orientation between two quad-faces was set to 4 (which is impossible if, a quad has 4 corners, we start with corner 0). This PR fixes it. 

fix orientation

---

src/t8_geometry/t8_geometry_implementations/t8_geometry_cad.cxx

The `t8_cmesh_get_attribute` function in `t8_geometry_cad::t8_geom_load_tree_data` got a global tree id, even though a local tree id is required by the function

Bug fix - Loading cad tree data

---

src/t8_element_c_interface.cxx
src/t8_element_c_interface.h
src/t8_element_cxx.hxx
src/t8_forest/t8_forest_cxx.cxx
src/t8_schemes/t8_default/t8_default_hex/t8_default_hex_cxx.cxx
src/t8_schemes/t8_default/t8_default_hex/t8_default_hex_cxx.hxx
src/t8_schemes/t8_default/t8_default_line/t8_default_line_cxx.cxx
src/t8_schemes/t8_default/t8_default_line/t8_default_line_cxx.hxx
src/t8_schemes/t8_default/t8_default_prism/t8_default_prism_cxx.cxx
src/t8_schemes/t8_default/t8_default_prism/t8_default_prism_cxx.hxx
src/t8_schemes/t8_default/t8_default_pyramid/t8_default_pyramid_cxx.cxx
src/t8_schemes/t8_default/t8_default_pyramid/t8_default_pyramid_cxx.hxx
src/t8_schemes/t8_default/t8_default_quad/t8_default_quad_cxx.cxx
src/t8_schemes/t8_default/t8_default_quad/t8_default_quad_cxx.hxx
src/t8_schemes/t8_default/t8_default_tet/t8_default_tet_cxx.cxx
src/t8_schemes/t8_default/t8_default_tet/t8_default_tet_cxx.hxx
src/t8_schemes/t8_default/t8_default_tri/t8_default_tri_cxx.cxx
src/t8_schemes/t8_default/t8_default_tri/t8_default_tri_cxx.hxx
src/t8_schemes/t8_default/t8_default_vertex/t8_default_vertex_cxx.cxx
src/t8_schemes/t8_default/t8_default_vertex/t8_default_vertex_cxx.hxx
test/Makefile.am
test/t8_forest/t8_gtest_find_owner.cxx
test/t8_schemes/t8_gtest_descendant.cxx
test/t8_schemes/t8_gtest_dfs_base.hxx
test/t8_schemes/t8_gtest_face_neigh.cxx
test/t8_schemes/t8_gtest_init_linear_id.cxx
test/t8_schemes/t8_gtest_root.cxx
test/t8_schemes/t8_gtest_successor.cxx

Introduce an element function that fills an element with the root element. 
Also replaces all occurences of `t8_element_set_linear_id (elem, 0, 0)` by `t8_element_root`.

Feature t8 element root

---

test/t8_cmesh_generator/t8_cmesh_example_sets.hxx
test/t8_cmesh_generator/t8_cmesh_parametrized_examples/t8_cmesh_new_empty.hxx

Added empty cmeshes to new test-suite

Added empty cmeshes

---

scripts/find_disabled_tests.scp
test/t8_cmesh/t8_gtest_cmesh_copy.cxx
test/t8_forest/t8_gtest_ghost_delete.cxx
test/t8_forest_incomplete/t8_gtest_empty_global_tree.cxx

Updated our testsuite to match the updated guideline for test-driven development. 
Also added a script that finds all disabled tests. 

Disable tests instead of skipping them

---

src/t8_cmesh.h
src/t8_cmesh/t8_cmesh.c
src/t8_cmesh/t8_cmesh_commit.c

Separates the negative volume check from the cmesh is committed check as discussed.

Split cmesh commit and geometry checks

---

test/t8_cmesh_generator/t8_cmesh_example_sets.hxx
test/t8_cmesh_generator/t8_cmesh_parametrized_examples/t8_cmesh_new_periodic.hxx
test/t8_cmesh_generator/t8_cmesh_parametrized_examples/t8_cmesh_params.hxx

Add periodic cmesh examples to our new cmesh tests

Add new_periodic examples

---

example/geometry/t8_example_geometries.cxx
src/t8_geometry/t8_geometry_base.hxx
src/t8_geometry/t8_geometry_implementations/t8_geometry_analytic.cxx
src/t8_geometry/t8_geometry_implementations/t8_geometry_analytic.h
src/t8_geometry/t8_geometry_implementations/t8_geometry_analytic.hxx
src/t8_geometry/t8_geometry_implementations/t8_geometry_cad.cxx

Fixes the geometry example. It did not work in debug due to the missing implementations of the negative volume check.

Fix geometry example

---

src/t8_cmesh/t8_cmesh.cxx

The memory of the geometry handler wasn't freed correctly. 

Delete geometry handler instead of calling the destructor

---

src/Makefile.am
src/t8_mat.h

t8_vec.h is an installed header, t8_mat.h should also be

Move t8_mat to installed headers

---

test/t8_geometry/t8_geometry_implementations/t8_gtest_geometry_lagrange.cxx
test/t8_geometry/t8_geometry_implementations/t8_gtest_geometry_linear.cxx
test/t8_gtest_macros.hxx

Use a Makro to avoid redefining the variable num_points over and over again. 

Introduce Makro to controll the number of points used for testing

---

test/t8_geometry/t8_geometry_implementations/t8_gtest_geometry_lagrange.cxx

There was some output from debugging left in the Lagrange test

Remove debugging output from Lagrange test

---

src/Makefile.am

I tried to link against an installed t8code, but it does not work if the handler is not part of the interface

Add handler to installed headers

---

test/CMakeLists.txt
test/Makefile.am
test/t8_gtest_occ_linkage.cxx

The occ linkage test was accidentally renamed to cad

Rename occ test

---

src/t8_geometry/t8_geometry_implementations/t8_geometry_lagrange.cxx

The lagrange geometry used the global tree id in its call to `t8_cmesh_get_attribute`, but it requires the local tree id.

Replace global by local tree id in call to t8_cmesh_get_attribute

---

src/t8_cmesh.h

Change "Co" to "Do" in a comment.
Also "param" was misspelled so that doxygen did not generate the descritption properly.

Fix a typo in a comment

---

configure.ac

When building the tarball for the next release, tar could not compress files with more than 99 characters in their name (including folder names).
We update AM_INIT_AUTOMAKE call to use a "better" version of tar that supports these long file names.

Feature update tar and automake version

---

src/t8_geometry/t8_geometry_implementations/t8_geometry_lagrange.cxx
src/t8_geometry/t8_geometry_implementations/t8_geometry_lagrange.hxx
test/t8_geometry/t8_geometry_implementations/t8_gtest_geometry_lagrange.cxx

`uint` is not supported by all compilers/platforms. This PR renames the few occurrences to `uint32_t`.

Renamed uints to the more commong uint32_t datatype.

---

src/t8_cmesh.h
src/t8_cmesh/t8_cmesh.cxx
src/t8_geometry/t8_geometry.cxx
src/t8_geometry/t8_geometry.h
src/t8_geometry/t8_geometry_implementations/t8_geometry_analytic.h

`bool` keyword in C header files creates trouble for the `Clang.jl` Julia package. The latter is needed for creating the Julia wrapper `T8code.jl`. This PR replaces `bool` with `int` in C header files.

Remove `bool` keyword from C header files

---

configure.ac

Add macro --enable-fortran and Fortran flags as a first step for the Fortran interface.

Add enable-fortran

---

src/t8_forest/t8_forest_cxx.cxx
src/t8_forest/t8_forest_general.h
test/t8_forest/t8_gtest_forest_face_normal.cxx

Title says it all. This is a convenience argument for the user base of t8code.

Feature: Optionally compute face orientation when calling leaf_face_neighbor routine.

---

CMakeLists.txt

Adds the option to use the system sc and p4est rather than the submodules

cmake: Add option to use system sc and p4est

---

src/t8_cmesh/t8_cmesh_helpers.cxx
src/t8_cmesh/t8_cmesh_helpers.h

Allows calling set join by vertices without the need of the eclasses and vertices array. The information is extracted from the cmesh stash instead

Set join by stash

---

example/geometry/t8_example_geometries.cxx
src/t8_geometry/t8_geometry_base.hxx
src/t8_geometry/t8_geometry_implementations/t8_geometry_analytic.h
src/t8_geometry/t8_geometry_implementations/t8_geometry_analytic.hxx
src/t8_geometry/t8_geometry_implementations/t8_geometry_cad.hxx
src/t8_geometry/t8_geometry_implementations/t8_geometry_examples.hxx
src/t8_geometry/t8_geometry_implementations/t8_geometry_linear.hxx
src/t8_geometry/t8_geometry_implementations/t8_geometry_linear_axis_aligned.hxx
src/t8_geometry/t8_geometry_implementations/t8_geometry_zero.hxx

Latex comments have to be embraced by "\f$" and not "/f$". This PR changes all occurens of false latex-markers. 

/f$ -> \f$ for latex documentation

---

CMakeLists.txt
doc/CMakeLists.txt
doc/Doxyfile.in
src/CMakeLists.txt

Added an option to build doxygen documentation from cmake

Add doxygen generation to cmake

---

tutorials/general/t8_tutorial_build_cmesh.cxx

Corrected the orientation parameter in the 3D example between element 4 and 5 from 0 to 2.
The parameter in the wiki article was already changed.

Correct orientation parameter in tutorial

---

src/t8_data/t8_containers.cxx
src/t8_data/t8_containers.h
src/t8_forest/t8_forest.c
src/t8_forest/t8_forest_adapt.cxx
src/t8_forest/t8_forest_cxx.cxx
src/t8_forest/t8_forest_ghost.cxx
src/t8_forest/t8_forest_iterate.cxx
src/t8_forest/t8_forest_partition.cxx
src/t8_forest/t8_forest_private.c
src/t8_forest/t8_forest_private.h

- Added const parameters to all functions where possible of the element array class.
- Added additional "_mutable" versions of function if it was necessary to have a non-const version besides a const version.
- Applied the changes throughout t8code

More const parameter for our element array class [1/3].

---

src/t8_forest/t8_forest_cxx.cxx

This PR fixes the following mwe, that runs into the wrong assertion on 8 procs.
On empty procs, first_tree might equal num_trees.
```
#include <t8.h>
#include <t8_cmesh/t8_cmesh_examples.h>
#include <t8_schemes/t8_default/t8_default_cxx.hxx>
#include <t8_forest/t8_forest_general.h>
static void
t8_mwe_cmesh_partition (){
int level = 1;
t8_cmesh_t cmesh = t8_cmesh_new_hypercube(T8_ECLASS_LINE, sc_MPI_COMM_WORLD, 0, 0, 0);
t8_cmesh_t partitioned_cmesh;
t8_cmesh_init(&partitioned_cmesh);
t8_scheme_cxx_t *ts = t8_scheme_new_default_cxx();
t8_scheme_cxx_ref(ts);
t8_cmesh_set_derive(partitioned_cmesh, cmesh);
t8_cmesh_set_partition_uniform(partitioned_cmesh, level, ts);
t8_cmesh_commit(partitioned_cmesh, sc_MPI_COMM_WORLD);
t8_forest_t forest = …
```

Fix offset assertion, for empty procs first tree is allowed to equal num trees

---

.github/workflows/add_release_documentation.yml
.github/workflows/update_documentation.yml

The checkout action now needs a `fetch-tags` option to fetch the tags

Fix documentation

---

src/t8_forest/t8_forest_cxx.cxx
src/t8_forest/t8_forest_private.h

Currently, for vertex elements, t8_forest_min_nonempty_level results in (int)ceil(log(a)/log(1)), which is not defined.
As for vertex trees, no level gains additional elements, and no level results in all nonempty procs, we return -1.

Adjust behaviour for forests with vertex elements for t8_forest_min_nonempty_level 

---

test/t8_forest/t8_gtest_element_is_leaf.cxx
test/t8_forest_incomplete/t8_gtest_iterate_replace.cxx

The test test/t8_forest_incomplete/t8_gtest_iterate_replace failed on Mac and had memory issues on Ubuntu.
The problem was a wrong reference handling of a cmesh as test variable.
The cmesh was associated with a forest and the forest changed the cmesh due to partitioning.
During clean up the test tried to remove the original cmesh (which did not exist any longer) instead of removing the new, changed cmesh.
The same logical error occured in the new element_is_leaf test as well.
If the Pull request introduces code that is not …

Fix 1083 iterate replace test failing

---

src/t8_forest/t8_forest.c
test/t8_cmesh/t8_gtest_cmesh_set_join_by_vertices.cxx
test/t8_cmesh_generator/t8_cmesh_parametrized_examples/t8_cmesh_new_hypercube_param.hxx

For a long time, we had the partitioned cmeshs disabled, since tests were failing.
This PR enables them again. Some tests still fail on 8 procs, but this is being worked on

enable partitioned cmeshs in tests

---

src/t8_forest/t8_forest.c
test/t8_cmesh/t8_gtest_cmesh_set_join_by_vertices.cxx
test/t8_cmesh_generator/t8_cmesh_parametrized_examples/t8_cmesh_new_hypercube_param.hxx

Reverts DLR-AMR/t8code#1103
The tests were failing on main.

Revert "enable partitioned cmeshs in tests"

---

src/t8_cmesh.h
src/t8_cmesh/t8_cmesh_commit.cxx

t8_cmesh_set_partition_uniform is only allowed to be called when deriving a cmesh, since when commiting from stash we do not know which proc is responsible for which part of the tree information. 

Add doc and check for t8_cmesh_set_partition_uniform

---

src/t8_data/t8_shmem.c

Change "used" to "use" in warning message.

fix a typo in a warning message

---

src/t8_cmesh.h
src/t8_cmesh/t8_cmesh.cxx
src/t8_cmesh/t8_cmesh_trees.c

Added a few more const' s to t8_cmesh.cxx

More const in t8_cmesh

---

src/t8_cmesh/t8_cmesh_commit.cxx

only t8_cmesh_add_attributes allowed for more const parameters in this file.

More const in t8-cmesh_commit

---

src/t8_cmesh/t8_cmesh_copy.c
src/t8_cmesh/t8_cmesh_geometry.cxx
src/t8_cmesh/t8_cmesh_netcdf.c
src/t8_cmesh/t8_cmesh_offset.c
src/t8_cmesh/t8_cmesh_partition.cxx

Added const into the signatures of the functions in t8-cmesh_partition.cxx

More const for t8_cmesh_partition

---

src/t8_cmesh/t8_cmesh_partition.cxx

Found a small TODO and fixed it. 
Allreduce percentages in debug-mode and check if they add up to 100 for cmesh_partition_percentage. 

Fix a small TODO

---

src/t8_cmesh/t8_cmesh.cxx
src/t8_cmesh/t8_cmesh_stash.c
src/t8_cmesh/t8_cmesh_stash.h

Scanned cmesh stash for more const parameters and trickeled down some const parameters from stash_add_attribute. 

More const cmesh stash

---

src/t8_cmesh/t8_cmesh_trees.c
src/t8_cmesh/t8_cmesh_trees.h

More const parameters for trees. 

More const for trees

---

CMakeLists.txt
benchmarks/CMakeLists.txt
example/CMakeLists.txt
tutorials/CMakeLists.txt

This PR changes the CMake build system to install all binaries (tutorials, examples) in the /bin folder instead of in separate tutorials/ and example/ folders to mimic the autotools build system and adds an option to compile benchmarks as well.

CMake: fix install folder structure and added option to compile benchmarks

---

test/t8_forest_incomplete/t8_gtest_iterate_replace.cxx

The test test/t8_forest_incomplete/t8_gtest_iterate_replace crashed on more than 2 processes.
This happened because the refinement rule removed all elements of a tree, which is not supported.
I changed the refinement rule such that the first element of a tree is always kept.

Fix incomplete trees test.

---

Makefile.am
config/t8_mpi.m4
configure.ac

Add a new configure option "custom-test-command".
This is the command use to run test. So setting it to "mpirun -np 8" will execute the tests with 8 processes.
Related to #1134 

Feature enable more procs for check

---

CMakeLists.txt
src/CMakeLists.txt

This is another CMake option, if enabled. adds `-Wall -pedantic -Werror`. This is the same set of flags used in the GitHub CI right now.

Adding CMake pedantic build mode option.

---

benchmarks/CMakeLists.txt
benchmarks/Makefile.am
benchmarks/time_new_refine.c

Closes #689. This PR cleans up the benchmark `time_new_refine.c` by updating it to make it compile using the latest API changes and removing `#if 0` `#endif` preprocessor macros.
As this benchmark was commented out of the build system for a long time, I do not know if it is still relevant.

Cleanup benchmark time_new_refine

---

src/t8_cmesh/t8_cmesh_partition.cxx
src/t8_cmesh/t8_cmesh_trees.c
src/t8_cmesh/t8_cmesh_trees.h

Closes #1163 renaming the macros T8_TREE_FIRST_ATT and T8_GHOST_FIRST_ATT to T8_TREE_FIRST_ATT_INFO and T8_GHOST_FIRST_ATT_INFO.

Rename T8_TREE/GHOST_FIRST_ATT to T8_TREE/GHOST_FIRST_ATT_INFO

---

src/t8_geometry/t8_geometry_helpers.c
src/t8_geometry/t8_geometry_helpers.h

The comment for t8_geom_linear_interpolation stated that it was using barycentric coordinates when in fact it was using cartesian coordinates.
Fixed the comment.
Also added empty lines to increase readability.

Fix comment of t8_geom_linear_interpolation

---

.github/workflows/tests_t8code_linkage_parallel_debug.yml
.github/workflows/tests_t8code_linkage_parallel_release.yml

I made some changes in the docker container of our CI and as soon as it gets pushed the CI will fail for t8code. This PR fixes that.

Adapt CI to changes in docker container

---

CMakeLists.txt
cmake/CheckNetCDFPar.cmake
src/CMakeLists.txt

This PR adds a check in the CMake build system for the `netcdf_par.h` header file.
Closes #1191

CMake: add check for netcdf_par.h header file

---

src/t8_geometry/t8_geometry_implementations/t8_geometry_examples.hxx

I made a bigger PR [here](https://github.com/DLR-AMR/t8code/pull/1205). This PR lets cmesh commit check, if a geometry is valid with the current cmesh. For this the geometries get a function which checks a tree for validity. I am not really sure if I implemented it correctly for your geometries, so it would be nice if you can take a look at this. Furthermore it would be nice if you could implement such a function for your new geometry int this PR:
https://github.com/DLR-AMR/t8code/pull/1185
If the Pull request introduces …

Add tree compatibility test for example cmesh geoms

---

src/t8_vtk/t8_vtk_writer_helper.hxx

On some systems there is a unused variable when not building with vtk, since it is only used in a vtk function. This macro solves that.

Fix a warning

---

CMakeLists.txt

It is not required to link with the whole vtk library. 
This pr only links with the necessary components when using CMake. 
Closes #1207 

only search for components of the vtk library

---

CMakeLists.txt
test/CMakeLists.txt

Add a default value to run the test-suite 2

---

.github/workflows/tests_cmake_sc_p4est.yml
.github/workflows/tests_cmake_t8code.yml
.github/workflows/tests_cmake_t8code_linkage.yml

Somehow this makes the tests slower.
Local testing resulted that parallel execution of tests is orders of magnitudes slower than serial test runs.
```
ctest
ctest -j
ninja test
ninja test -j
ninja test -j<N>
```
execute each test after the previous one and are significantly faster than `ctest -j<N>`. Removed the $MAKEFLAGS from the test so there is no confusion that this executes the tests in parallel
Reverts DLR-AMR/t8code#1226

Revert "Enable parallel tests in cmake ci"

---

CMakeLists.txt

Currently, the default build type in ccmake is not shown and the cmake build type is empty from the start. If it remains empty, release is chosen. This PR changes that, so release is displayed from the start and cannot be left empty.
Furthermore the docstring now lists our available build types, before it was the standard message which also listed MinSizeRel, which is not available in our list.

Enhance default build type selection

---

src/t8_cmesh/t8_cmesh_examples.cxx
src/t8_geometry/t8_geometry_implementations/t8_geometry_examples.cxx
src/t8_vtk/t8_vtk_write_ASCII.cxx

This is a litte PR to fix some compiler errors regarding the misuse of `constexpr` ~and also a small format string error/warning~.
Closes https://github.com/DLR-AMR/t8code/issues/1240.

Fix const expr compilation errors

---

example/IO/cmesh/gmsh/t8_read_msh_file.cxx
example/IO/forest/gmsh/t8_gmsh_to_vtk.cxx

Fix a typo

---

src/t8_vtk/t8_vtk_writer.hxx

write_element_id was missing in the initializer list. This PR fixes it. 

Add write_element_id to initializer-list

---

scripts/t8indent

Until now we specifically ask for clang-format `17.0.1`, but conda is not able to install this version without tricks.
I checked the different patch versions of `17.0` and they all indent the same way. Therefore, I would open our hard limit to version `17.0` instead of `17.0.1`

Allow more clang-format versions

---

doc/author_albers.txt
tutorials/general/t8_tutorial_build_cmesh.cxx

The tutorial isn't included in the numbering, therefore the output-file should not be numbered as well. 
The prefix of the output was changed from "t8_step8_user_defined_mesh_..." to "t8_user_defined_mesh_...".

Cleanup tutorial build cmesh

---

src/t8_forest/t8_forest_general.h

The documentation of t8_forest_leaf_face_neighbors had a typo and described a parameter that is not present in the function declaration.
Corrected the typo and removed the parameter.
Slightly related to #1269 

Correct documentation of t8_forest_leaf_face_neighbors.

---

CITATION.cff
test/t8_gtest_version.cxx

Update the CITATION file and version tests

version 3.0.0

---

src/t8_geometry/t8_geometry_implementations/t8_geometry_examples.hxx

Fix wrong return value when checking tree geometry compat.

---

example/version/t8_version.cxx
src/t8_cmesh/t8_cmesh_readmshfile.cxx
src/t8_data/t8_data_handler.hxx
src/t8_geometry/t8_geometry_implementations/t8_geometry_examples.cxx
test/t8_data/t8_pseudo_trees.hxx

Internal data is processed in the background without the user noticing or being restricted.

add placeholder for internal data handling

---

src/t8_geometry/t8_geometry_implementations/t8_geometry_analytic.h
src/t8_geometry/t8_geometry_with_vertices.h

This PR adds missing includes for used definitions. This leads to wrong translations for the Julia bindings.
This is related to:
https://github.com/DLR-AMR/t8code/pull/891
https://github.com/DLR-AMR/T8code.jl/issues/47
https://github.com/DLR-AMR/T8code.jl/pull/78
https://github.com/trixi-framework/Trixi.jl/actions/runs/12182527496/job/33981760954?pr=1844#step:7:11266

Fix: Add missing headers in order to import definitions.

---

.github/workflows/tests_cmake_t8code.yml
.github/workflows/tests_cmake_t8code_api.yml
.github/workflows/tests_cmake_t8code_linkage.yml
.github/workflows/tests_cmake_t8code_w_shipped_submodules.yml

Increase the timeout limit for our CI tests

Increase ci timeout limit

---

.github/workflows/tests_cmake_t8code.yml
.github/workflows/tests_cmake_t8code_api.yml
.github/workflows/tests_cmake_t8code_linkage.yml
.github/workflows/tests_cmake_t8code_w_shipped_submodules.yml

increase ci timeout limit (again)

---

.github/workflows/tests_cmake_t8code_api.yml

I think that this option is not properly parsed to the configure command. Moving it to the CONFIG_OPTIONS variable hopefully solves this issue.

Move fortran debug flag

---

test/t8_gtest_custom_assertion.hxx
test/t8_schemes/t8_gtest_face_neigh.cxx
test/t8_schemes/t8_gtest_successor.cxx

Found some places where we used the old ASSERT_TRUE(scheme->elem_eq)

fixed missing Assertion

---

src/t8_schemes/t8_default/t8_default_common/t8_default_common.hxx
src/t8_schemes/t8_scheme.hxx

The schemes eclass data member is now accessed via a getter function and not directly. This way schemes dddo not have to have an eclass data member and it also become immutable.

Add getter for scheme eclass

---

src/t8_vtk/t8_vtk_writer.h

The function t8_forest_to_vtkUnstructuredGrid was declared twice in the same file. This removes the undocumented declaration.

Remove duplicate declaration

---

src/t8_schemes/t8_default/t8_default_prism/t8_dprism_bits.c
src/t8_schemes/t8_default/t8_default_pyramid/t8_dpyramid_bits.c

I found some dynamic allocations where the length of the array is already known at compile time and got rid of the dynamic allocation. 

Avoid dynamic allocation in element-functions

---

src/t8_cmesh/t8_cmesh_commit.cxx
src/t8_forest/t8_forest_netcdf.cxx

Following #1347 I did a quick search over our base looking for T8_ALLOCs with Makros or hard coded numbers in it. This is what I found. 

Avoid dynamic allocations with hard-coded numbers

---

src/CMakeLists.txt
src/t8_schemes/t8_default/t8_default_quad/t8_default_quad.cxx
src/t8_schemes/t8_default/t8_default_quad/t8_default_quad.hxx
src/t8_schemes/t8_default/t8_default_quad/t8_default_quad_bits.cxx
src/t8_schemes/t8_default/t8_default_quad/t8_default_quad_bits.hxx
src/t8_schemes/t8_default/t8_default_quad/t8_dquad.h

The default quad scheme uses the `t8_pquad_t` data type (internally mapped to `p4est_quadrant_t`).
One header defined the data type `t8_dquad_t` ("d" instead of "p") completely differently and used it in the function `t8_dquad_compute_reference_coords` where it was wrongly casted into a `t8_pquad_t`.
This is a serious data conversion bug that may have caused issue in the past.
What we did to resolve it:
- Remove `t8_dquad_t` since it was not used elsewhere
- Use `t8_pquad_t` instead
- Rename the files `src/t8_schemes/t8_default/t8_default_quad/t8_dquad_bits.cxx` to `src/t8_schemes/t8_default/t8_default_quad/t8_default_quad_bits.cxx` to avoid name confusion in the future.
**_All these boxes must be checked by the reviewers before merging the pull …

Fix dquad/pquad confusion bug

---

src/t8_schemes/t8_default/t8_default_hex/t8_default_hex.hxx
src/t8_schemes/t8_default/t8_default_line/t8_default_line.hxx
src/t8_schemes/t8_default/t8_default_prism/t8_default_prism.hxx
src/t8_schemes/t8_default/t8_default_pyramid/t8_default_pyramid.hxx
src/t8_schemes/t8_default/t8_default_quad/t8_default_quad.hxx
src/t8_schemes/t8_default/t8_default_tet/t8_default_tet.hxx
src/t8_schemes/t8_default/t8_default_tri/t8_default_tri.hxx
src/t8_schemes/t8_default/t8_default_vertex/t8_default_vertex.hxx
src/t8_schemes/t8_scheme.hxx
test/CMakeLists.txt
test/t8_schemes/t8_gtest_ancestor.cxx
test/t8_schemes/t8_gtest_ancestor_id.cxx

Add element ancestor test

---

CMakeLists.txt

Following the update of libsc, this PR replaces the old `mpi` cmake option with the cleaner `SC_ENABLE_MPI` option

Remove old libsc option

---

src/t8_schemes/t8_default/t8_default_prism/t8_dprism_bits.c

In the `children_at_face` function the documentation specifies, that "It is valid to call this function with elem = children[0]." 
This wasn't true for this function as proven with a new test, which will be introduced with the standalone scheme face functions. 
With the reversion of the loop, the input element at children[0] is overwritten in the last step, which is intended. 

 Revert loop to prevent overwriting of the input element

---

JOSS/paper.bib
JOSS/paper.md

minor changes for JOSS publication

---

src/t8_vtk/t8_vtk_writer.hxx

Add more setters to the vtk-writer. That way a single vtk writer is sufficient to write in various configurations. 

introduce more setters to the vtk writer

---

JOSS/paper.bib

final? minor change in paper.bib

---

src/t8_schemes/t8_default/t8_default_quad/t8_default_quad.cxx

In the `element_extrude_face` function the `element_is_valid` function is called for the wrong element. In the corrected line `face` needs to be checked. 

Fix error in default quad scheme

---

src/t8_cmesh/t8_cmesh_examples.cxx

As mentioned in Issue #79 the bug is fixed and therefore the warning is outdated an can be removed. 

Remove partition warning

---

doc/author_nguyenxuan.txt
example/IO/cmesh/vtk/t8_cmesh_read_from_vtk.cxx

Fixed the documentation in the `t8_cmesh_read_from_vtk` file

Fixed vtk read documentation

---

doc/author_ploetzke.txt
src/t8_forest/t8_forest_general.h
tutorials/general/t8_step2_uniform_forest.cxx
tutorials/general/t8_step3_adapt_forest.cxx
tutorials/general/t8_step4_partition_balance_ghost.cxx
tutorials/general/t8_step5_element_data.cxx

- In the documentation of the adapt, partition and balance functions, it was stated that the order of execution is always 1) Adapt 2) Balance 3) Partition, although it is 1) Adapt 2) Partition 3) Balance.
- Fixed some typos in the tutorials. 
- Added one productionf in step 4.

Correct order of execution in docu and some typos

---

test/CMakeLists.txt

Fix compile error by linking to Gtest as system-library. 

link to gtest as system-library

---

.github/workflows/build_cmake_tarball.yml
.github/workflows/check_indentation.yml
.github/workflows/mattermost_issue.yml
.github/workflows/mattermost_pull_request.yml

Update the GitHub runners because 20.04 is deprecated

Update GitHub Runners

---

src/t8_types/t8_operators.hxx
src/t8_types/t8_type.hxx
test/t8_types/t8_gtest_type.cxx

Made everything in the strong type constexpr and every competence that is constexpr, too. 

constexpr for strong types

---

src/t8_types/t8_operators.hxx

Fixes an ambiguity warning which prevents me from compiling this.
```
ISO C++20 considers use of overloaded operator '==' (with operand types 'const DummyInt' (aka 'const T8Type<int, dummy_int, Addable, Subtractable, AddAssignable, Multipliable, Dividable, PrefixDecrementable, PrefixIncrementable, EqualityComparable, Printable>') and 'const DummyInt') to be ambiguous despite there being a unique best viable function
```
Stackoverflow explanation:
The specific issue is that in C++20, comparison operators add a new notion of rewritten and reversed candidates. So lookup for the expression a == b will also end up matching operators like b == a. In the typical case, this means you have to write fewer operators, since we know equality is commutative.
But if you …

Fix operator warning

---

test/t8_cmesh_generator/t8_cmesh_example_sets.hxx
test/t8_cmesh_generator/t8_cmesh_parameterized_examples/t8_cmesh_new_bigmesh_param.hxx
test/t8_cmesh_generator/t8_cmesh_parameterized_examples/t8_cmesh_new_comm.hxx
test/t8_cmesh_generator/t8_cmesh_parameterized_examples/t8_cmesh_new_disjoint_bricks_param.hxx
test/t8_cmesh_generator/t8_cmesh_parameterized_examples/t8_cmesh_new_empty.hxx
test/t8_cmesh_generator/t8_cmesh_parameterized_examples/t8_cmesh_new_from_class_param.hxx
test/t8_cmesh_generator/t8_cmesh_parameterized_examples/t8_cmesh_new_hypercube_param.hxx
test/t8_cmesh_generator/t8_cmesh_parameterized_examples/t8_cmesh_new_periodic.hxx
test/t8_cmesh_generator/t8_cmesh_parameterized_examples/t8_cmesh_new_prism_cake_param.hxx

- Problem was that scheme was appended without _ (-> added_)
- and we had two underscores for all other test (as names ended with _ and the functions make_param_string startet with a delimiter. I chose to remove the _ from the names.

Remove doubled underscores in test names

---

src/t8_cmesh/t8_cmesh_examples.h
test/t8_cmesh_generator/t8_cmesh_parameterized_examples/t8_cmesh_params.hxx
test/t8_forest/t8_gtest_forest_commit.cxx
test/t8_forest/t8_gtest_ghost_exchange.cxx
test/t8_forest_incomplete/t8_gtest_iterate_replace.cxx
test/t8_schemes/t8_gtest_nca.cxx

- Typos and indentation
- removed some unused code
- remove one old todo comment (related function does not exist anymore)

Correct some typos and remove unused code

---

.github/workflows/check_indentation.yml
.github/workflows/spell_check.yml
.github/workflows/tests_cmake_testsuite.yml

Closes #1425 
For a detailed description, please have a look at the Issue. We decided to optimize our CI, this branch implements the decision that we made. 
TODOS:

Improve CI to a more finegrained CI

---

test/t8_forest_incomplete/t8_gtest_iterate_replace.cxx

This test was around 17s vs max 3s for the other tests at TEST_LEVEL 2.

Reduce runtime for TEST_LEVEL == 2

---

scripts/check_macros.scp

Added missing copyright statement in check_macros script

---

.github/workflows/tests_cmake_testsuite.yml

Pull request would stall when they are changed from Draft-PR to a proper PR. 
We can fix this by also running the CI when the event ready_for_review is triggered. 

also run the CI when a Draft-PR is converted into a PR

---

scripts/pre-commit

The pre-commit script did not work as there was a typo.

Fix typo in pre-commit script

---

test/t8_geometry/t8_geometry_implementations/t8_gtest_geometry_linear.cxx

The valgrind check for all test files developed in #1453 detected a memory leak in this test. The changes here fix the problem.

Bugfix: Memory leak in test t8_gtest_geometry_linear

---

src/t8_geometry/t8_geometry_implementations/t8_geometry_lagrange.cxx

The valgrind check for all test files developed in #1453 detected an invalid read size in the test t8_geometry/t8_geometry_implementations/t8_gtest_geometry_lagrange_serial. The changes here fix the problem.

Bugfix: Invalid read size

---

src/t8_forest/t8_forest_general.h
src/t8_forest/t8_forest_private.h

Move element_find_owner to public interface

---

src/t8_vtk/t8_vtk_writer_helper.cxx

The vtk writer function `num_cells_to_write` computed the wrong value for forests.
For forests it computed "#local_elements + #ghost_trees" instead of "#local_elements + #ghost_elements".
This can be tested with `test/t8_IO/t8_gtest_vtk_writer_parallel` if ghost writing is enabled in the test (see also upcoming PRs and #1489 #1488).
If the Pull request introduces code that is not covered by the github action (for example coupling with a new …

Bugfix: vtk writer num_cells_to_write [1/3]

---

src/CMakeLists.txt

Solves #1461. So far, when installing t8code using CMake, all headers were added to `<my_install_dir>/include/`. This PR keeps those header files supposed to be for internal use only from getting copied to the install directory. This list of excluded headers is taken from the `Makefile.am` of the autoconf build.

Improvement: Dinstinguish internal header files from public ones

---

.github/workflows/tests_cmake_testsuite.yml
.github/workflows/tests_cmake_valgrind.yml
scripts/README.md
scripts/check_all_test_binaries_valgrind.sh
scripts/find_all_test_binary_paths.sh

Previously, the find_all_test_binaries file found a file that was not built with all options, resulting in an error. The new implementation actually lists the executables in the build/test/ directory. 
Also, the timeout had to be increased as the time of the test suite at test level 2 increased.
Closes #1441 

Bugfix: Change strategy to find test binaries for valgrind ci

---

src/t8_schemes/t8_default/t8_default_prism/t8_dprism_bits.c

This PR addresses an issue with `element_set_linear_id` I encountered for the default prism scheme. For example, when running 
```
t8_element_t *element;
ts->element_new (eclass, 1, &element);
ts->element_set_linear_id (eclass, element, 21, 2305843009213693952);
t8_linearidx_t linearid = ts->element_get_linear_id (eclass, element, 21);
```
with the respective eclass and scheme and 2305843009213693952 being the global first descendant of child 2 on level 1, `linearid` would evaluate to 0 instead of the input linearid. This seems to be caused by `triangles_of_size_i` which overflows and evaluates to 0 at some point in `t8_dprism_init_linear_id`. By switching its type to t8_linearidx_t the above code yielded the expected results.
**_All these boxes must be checked by the AUTHOR before …

Fix set_linear_id for prisms

---

.github/workflows/issue_event_moves_card.yml
.github/workflows/move_card.yml
.github/workflows/pr_event_moves_card.yml
.github/workflows/quick_pr.yml

Closes #1510
This adds 4 files to automize project boards. A full documentation of what they do can be found [here](https://github.com/DLR-AMR/workflows_for_GH_projects). 
The file move_card evaluates issue and PR triggered events and decides where a card that is related to the issue/PR should be moved. 
Issue_event_moves_card is called by move_card if an issue-event has been triggered and moves the card to a specified column. 
PR_event is called by move_card if a pr_event has been triggered. It also checks if the issue and PR are realy related, because issue-numbers are only unique on repository level, not on organization level. 
Quick_PR is called if a PR does not reference an issue. A new Issue is opened and referenced by the PR. 
It also introduces one major change to our general …

Feature: Added workflow files to automize project board usage.

---

.github/workflows/move_card.yml

Special signs, empty spaces, etc could cause an error while processing the labels. 
If that happens we suppress the error-message (which lead to a failing wf) and add an empty string to the "labels"-variable instead. That way all following labels can be processed without the wf failing. 
Closes #1532 

Bugfix: More robust handling of labels

---

CMakeLists.txt

Closes #1571
Closes #1558 
Alternative solution to https://github.com/DLR-AMR/t8code/pull/1567

Automatically mark sc and p4est options as advanced

---

example/geometry/t8_example_geometries.cxx

Closes #1517
The tutorial did overwrite the `t8_geom_load_tree_data` function which loaded the active tree. Therefore, the active tree and compatible trees mismatched.

Bugfix: Fix geometry example

---

src/t8_forest/t8_forest.cxx

Closes #1585
When using t8code without VTK and trying to write a curved mesh we throw a warning which states that curved output is not available with VTK and that we now write uncurved with the inbuilt writer. Then an assertion hits before we write.
I removed this assertion because it does not have a purpose anymore.

Bugfix: Remove curved assertion

---

src/t8_cmesh/t8_cmesh.cxx

Closes #1616 
free the vertex_connectivity object in t8_cmesh_destroy to fix the memory leak. 

Bugfix: Fix memory leak. 

---

src/t8_schemes/t8_default/t8_default_common/t8_default_common.hxx
src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx

Closes #1621
closes #1624
The files t8_standalone_implementation.hxx and t8_default_common.hxx were missing an `#include <utitlity>` in order to use the function `std::exchange`.
This caused the code to not compile.
I added the includes to both headers.

Bugfix: Missing utility header include

---

src/t8_geometry/t8_geometry_implementations/t8_geometry_cad.cxx
test/t8_geometry/t8_gtest_point_inside.cxx

Closes #1627
Found an old indent guard

Other: Remove deprecated indent macro

---

src/t8_data/t8_shmem.c
src/t8_data/t8_shmem.h

Closes #1590
Improved the documentation of shmem_prefix-wrapper and added some assertions. 

Other: Improved documentation, more assertions

---

src/t8_types/t8_type.hxx
test/t8_types/t8_gtest_type.cxx

Closes #1664
Added implicit type conversion to base type to our strong types.
Marked [1/2] since it has to be merged before #1656 which uses this feature.
**Why?**
In some scenarios, in particular when we want to print out values for our strong types, we need to cast them back into their base type.
For example when strong types are used in GoogleTest assertion, GoogleTest requires the "<<" operator to work.
It happened to me when switching to a strong type for geometry hash usage (see #1656) and a part of the code was doing
`t8_debug_f ("Hash %lu not found\n", hash);` which did not compile since "hash" as a strong type was not convertible to "long unsigned".
**_All these boxes …

Feature: strong type conversion [1/2]

---

test/t8_cmesh_generator/t8_cmesh_example_sets.hxx
test/t8_forest/t8_gtest_element_is_leaf.cxx

Closes #1671
With the introduction of the standalone scheme, I modified the pretty print for some tests. But this was more of a quickfix.
Now the pretty print can be proud to call itself pretty again. 

Improvement: Improve test pretty print

---

test/CMakeLists.txt
test/t8_forest_incomplete/t8_gtest_iterate_replace.cxx

Closes #1648
Lets the test be executed in parallel in the CI. 
Decreases the levels that are tested to reduce the overall size of the tested forests. 

Improvement: Decrease test level

---

test/t8_schemes/t8_gtest_face_descendant.cxx

Closes #1645 
Reduce the depth of the computation of the first and last face descendant of an element. 
Furthermore it is now depending on the test level that has been set. 

Improvement: Reduce depth of descendant test

---

test/t8_forest/t8_gtest_element_is_leaf.cxx
test/t8_gtest_schemes.hxx

Closes #1646 
Adapts the original test to only be parametrized over all schemes, eclasses and a level. The functionality is tree specific and therefore does not need to run over all cmeshes in our testsuite. 
Adds a test for a all scheme collections to test if the right function is called in a hybrid forest. 

Improvement: Speed up element is leaf test

---

.github/workflows/tests_cmake_testsuite.yml

Closes #1686
Let the code coverage workflow run for every commit (in PRs, merge queue ... not in drafts as defined in fine_grained_trigger). 
As the code coverage workflow does not increase the overall run time of the testsuite massively, we can run the workflow for every commit. 

Improvement: Run code coverage workflow for every commit 

---

test/t8_schemes/t8_gtest_nca.cxx

Closes #1647 
changed a little the recursion depth. 
The most time was spend on the last test in the testsuite, because it always tested up to maxlvl. Reduced it down to maxlvl/2 for test levels other than 0. 

Improvement: Runtime of nca test

---

benchmarks/t8_time_forest_partition.cxx

Closes #1698
During the vector update some vector operations got mangled.
Fixed in accordance to this implementation: https://github.com/DLR-AMR/t8code/blob/20e7ae9494c081f9946868f38d31d9ce85c96c06/benchmarks/time_forest_partition.cxx#L66

Bugfix: Wrong vector operations in benchmark

---

benchmarks/t8_time_forest_partition.cxx

Closes #1709
In the benchmark `t8_time_forest_partition.cxx` a block of code was depreciated and not used by ´#if 0` eight years ago, so I would just remove it. 

Improvement: Remove depricated lines from benchmark

---

test/t8_cmesh/t8_gtest_cmesh_vertex_conn_tree_to_vertex.cxx

Closes #1718
I missed `T8_ALLOC`s in a new test during a merge.

Fix: Use testsuite alloc

---

test/CMakeLists.txt
test/t8_data/t8_gtest_data_handler.cxx

Closes #1720 
The time-out was caused by a blocking send/recv to self. 
I solved it by not sending/receiving to self. 

Bugfix: Do not send to self via blocking send

---

test/t8_schemes/t8_gtest_get_linear_id.cxx

Closes #1770
The linear id test used a `t8_locidx_t` to store linear ids and this of course overflows under specific circumstances.
Furthermore, the test now uses the actual element level for retrieving ids. Normally, this makes no difference, but in the multilevel scheme it does.

Bugfix: Overflowing datatype in test

---

src/t8_forest/t8_forest_search/t8_forest_search.cxx
src/t8_forest/t8_forest_search/t8_forest_search.hxx

This PR addresses some issues that I encountered while using the local search.
- In `check_queries` the query callback is called inside a `std::ranges::views::filter` used later to define the array `new_active_queries` based on the return value of the callback. On leaf level `new_active_queries` is not computed and due to lazy evaluation, the query callback is not executed on leaf level either. Furthermore, the assignment
`new_active_queries.assign (positive_queries.begin (), positive_queries.end ());`
leads to the same callback being evaluated twice for some indices. This PR replaces the evaluation by a copy_if, which seems to work fine, evaluating every callback exactly once.
- In `update_queries` and `check_queries` the active_queries array is swapped with the new_active_queries array. …

Bugfix: local search

---

src/t8_cmesh/t8_cmesh_readmshfile.cxx
src/t8_vtk/t8_vtk_write_ASCII.cxx

Closes #1790
From one day to the other I had some weird compiler errors which prevented me from building t8code.
For one I had to implement copy and move constructors/assignment operators and I do not know why.
The other error complained, that we want to close a file which is NULL, which made sense. But I do not know why this never came up before.
If the Pull request introduces code that is not covered by the github action (for example coupling …

Fix some weird compiler errors

---

.github/workflows/move_card.yml

Closes #1823
When two events are triggered very fast (pull_request & review_requested for example) the pr_action runs twice and might create two issues for the same PR. 
This change only allows one execution of the workflow per pull request (so different pull_request might trigger the action in parallel, but the same pull request will trigger the action sequentially). Therefore an issue will be assigned to the PR when the action runs again and a duplication of the issue should be prevented. 
As a reviewer please read through all the code lines and make sure that the code is *fully understood, bug free, well-documented and …

Bugfix: pr action

---

CMakeLists.txt

Closes #1795
I have the problem, that I have to build t8code with OpenMPI .
This works as long as I link to a self-build SC, because the arising warnings are within SC and Werror of t8code does not trigger.
But when I try to build t8code with the shipped SC, the warnings are part of t8code and Werror will kick in.
Therefore, i implemented a check which determines if OpenMPI was used and then suppresses that the warning for SC (not for t8code) is treated as an error.
The code builds an example program which checks if [this macro](https://github.com/open-mpi/ompi/blob/6a2c60aa00ef084a86955eb88e716635353500e5/ompi/include/mpi.h.in#L254-L257) was defined.
**_All these boxes must be …

Fix: OpenMPI linkage

---

src/t8_forest/t8_forest_search/t8_forest_search.cxx
src/t8_forest/t8_forest_search/t8_forest_search.h
src/t8_forest/t8_forest_search/t8_forest_search.hxx

Closes #1745 
Fixes all doxygen errors in t8_forest/t8_forest_search/*

fix doxygen in t8_forest/t8_forest_search

---

src/t8_schemes/t8_default/t8_default_common/t8_default_common.hxx
src/t8_schemes/t8_default/t8_default_hex/t8_default_hex.cxx
src/t8_schemes/t8_default/t8_default_hex/t8_default_hex.hxx
src/t8_schemes/t8_default/t8_default_line/t8_default_line.cxx
src/t8_schemes/t8_default/t8_default_line/t8_default_line.hxx
src/t8_schemes/t8_default/t8_default_line/t8_dline_bits.c
src/t8_schemes/t8_default/t8_default_line/t8_dline_bits.h
src/t8_schemes/t8_default/t8_default_prism/t8_default_prism.cxx
src/t8_schemes/t8_default/t8_default_prism/t8_default_prism.hxx
src/t8_schemes/t8_default/t8_default_pyramid/t8_default_pyramid.cxx
src/t8_schemes/t8_default/t8_default_pyramid/t8_default_pyramid.hxx
src/t8_schemes/t8_default/t8_default_pyramid/t8_dpyramid_bits.c
src/t8_schemes/t8_default/t8_default_quad/t8_default_quad.cxx
src/t8_schemes/t8_default/t8_default_quad/t8_default_quad.hxx
src/t8_schemes/t8_default/t8_default_tet/t8_default_tet.cxx
src/t8_schemes/t8_default/t8_default_tet/t8_default_tet.hxx
src/t8_schemes/t8_default/t8_default_tet/t8_dtet_bits.h
src/t8_schemes/t8_default/t8_default_tri/t8_default_tri.cxx
src/t8_schemes/t8_default/t8_default_tri/t8_default_tri.hxx
src/t8_schemes/t8_default/t8_default_tri/t8_dtri_bits.c
src/t8_schemes/t8_default/t8_default_tri/t8_dtri_bits.h
src/t8_schemes/t8_default/t8_default_vertex/t8_default_vertex.cxx
src/t8_schemes/t8_default/t8_default_vertex/t8_default_vertex.hxx

Closes #1861
Rename variables from t to element in t8 scheme default. Additionally, this makes the variable naming of some functions in the .hxx and .cxx files consistent.
Hope that i catched all t's.

Improvement: Rename variables from t to element in t8 scheme default

---

src/t8_forest/t8_forest_iterate.cxx

Closes #1863
Just a minor bugfix I stumbled over during the t8code week. Since it's actually changing code, I decided to separate it from the doxygen fixes.

Bugfix: Corrected outdated debug flag in t8_forest_iterate.cxx

---

src/t8_forest/t8_forest_balance.cxx
src/t8_forest/t8_forest_ghost.cxx
src/t8_forest/t8_forest_iterate.cxx

Closes #1869
This PR adds further documentation to static functions in the directory `src/t8_forest/`. They did not cause any doxygen errors, so I outsourced it into this PR. Logically, it is a follow-up of #1867 , but practically, it is independent.
- [] If the PR is related to an issue, make sure to link it.

Documentation: Add doxygen documentation to remaining static functions in folder src/t8_forest/

---

src/t8_forest/t8_forest_ghost.cxx

The `t8_forest_ghost` function uses `t8_global_productionf` to display messages with partition-local info (the number of elements and ghosts). This PR fixes this by replacing the call with its local counterpart `t8_productionf`.

Bugfix: global logging with local info in t8_forest_ghost
